### ISSUE TITLE
RPIEasy home automation software

### ISSUE THREAD

**Issue by happytm** [gcgarner/IOTstack#10]
Can you please bundle RPIEasy home automation framework ? RPIEasy covers most of common sensors.By including it will be perfect standalone or network solution for home automation. Link to RPIEasy is below:

https://github.com/enesbcs/rpieasy

Thanks.

**Comment by gcgarner** [comment]
I will have a look what i can do

**Comment by gcgarner** [comment]
By the looks of the project it would be better to be a native install. I'll test it by installing it alongside Node-RED to test the compatibility

**Comment by happytm** [comment]
Thanks.

**Comment by gcgarner** [comment]
I've done some preliminary testing and I'm had some success. I want to do more testing before I add it to the main project. I'm going to create a new Issue for native installs for this

**Comment by happytm** [comment]
Take your time.

Thanks.
