### ISSUE TITLE
Feature request - deconz 

### ISSUE THREAD

**Issue by recom273** [gcgarner/IOTstack#101]
Is there a way deconz could be included into the stack? Conbee and raspbee are a great bridge for homeassisitant and homebridge to access Zigbee devices.

I noticed there was a homebridge request? Have their been any developments? 

TIA

**Comment by gcgarner** [comment]
I havent gotten to homebridge yet, its on my list at least. Will have a look at deconz, i see there is an image for one already

Right now fist order of business now is getting nginx reverse proxy running properly, after i will add more images

**Comment by recom273** [comment]
Excellent!

Thanks for your reply.
