### ISSUE TITLE
Root password for MariaDB not accepted

### ISSUE THREAD

**Issue by ronnyandre** [gcgarner/IOTstack#102]
Fresh installed MariaDB container has the MariaDB root password set to the root password for the computer.

I get access denied when using correct password. I tried changing the password, just to make sure I didn't make any mistakes, but it still cannot log in.

**Comment by gcgarner** [comment]
The mariadb container only gives you one shot to set the passwords. If you ran `docker-compose up -d` and left the default settings in the maria.env file then they are set for good. No amount of changing the env file and restarting the container will change it. You will either need to go in via the terminal with the old password and create the databases and users or stop the mariadb container, remove its volume folder and run docker-compose up -d with the new env file.

note that if you didnt set anything in the env file you will be able to login with the details in the image below:

![image](https://user-images.githubusercontent.com/46672225/69872275-9ff56580-12bd-11ea-85ce-5a560313a435.png)

password is `ROOT_ACCESS_PASSWORD`

**Comment by gcgarner** [comment]
closing stale issue
