### ISSUE TITLE
How to modify Pihole password?

### ISSUE THREAD

**Issue by begerelli** [gcgarner/IOTstack#114]
I changed it in the ~/IOTstack/services/pihole/pihole.env like written in Wiki article,
but Pihole only accepts "pihole" as password.

Thanks in advance for every help.

**Comment by urosch** [comment]
Connect to pihole's container using console (using portainer for example) as root and issue a command: sudo pihole -a -p
Then enter new password twice, after the restart, the new password works ;)

**Comment by begerelli** [comment]
Many thanks, it worked with portainer.
