### ISSUE TITLE
Problem with Installing Nodes in script

### ISSUE THREAD

**Issue by Paulf007** [gcgarner/IOTstack#12]
OS - Raspbian Buster Lite (Clean Image)
Followed the Steps in the Manual 
When adding the various extra nodes for node red I got the following errors

> Status: Downloaded newer image for nodered/node-red:latest
 ---> b04b04ad7675
Step 2/2 : RUN for addonnodes in node-red-node-pi-gpiod node-red-dashboard node-red-node-google node-r                                                                                   ed-node-emoncms node-red-node-ping node-red-node-random node-red-node-smooth node-red-node-darksky nod                                                                                   e-red-contrib-influxdb node-red-contrib-config node-red-contrib-grove node-red-contrib-diode node-red-                                                                                   contrib-bigtimer node-red-contrib-esplogin node-red-contrib-timeout node-red-contrib-moment node-red-c                                                                                   ontrib-particle node-red-contrib-web-worldmap node-red-contrib-isonline node-red-contrib-npm node-red-                                                                                   contrib-file-function node-red-contrib-boolean-logic node-red-contrib-blynk-ws node-red-contrib-owntra                                                                                   cks ; do npm install ${addonnodes} ;done;
 ---> Running in d40bf44e3aa7
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-red-node-pi-gpiod@0.0.13
added 4 packages from 2 contributors and audited 1375 packages in 14.243s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-dashboard@2.17.1
added 47 packages from 42 contributors and audited 1491 packages in 18.853s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS                                                                                    issue
npm WARN deprecated hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as th                                                                                   is distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support p                                                                                   olicy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and                                                                                    security patches. If you are unable to upgrade at this time, paid support is available for older vers                                                                                   ions (hapi.im/commercial).
npm WARN deprecated cryptiles@3.1.4: This version has been deprecated in accordance with the hapi supp                                                                                   ort policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes                                                                                   , and security patches. If you are unable to upgrade at this time, paid support is available for older                                                                                    versions (hapi.im/commercial).
npm WARN deprecated boom@4.3.1: This version has been deprecated in accordance with the hapi support p                                                                                   olicy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and                                                                                    security patches. If you are unable to upgrade at this time, paid support is available for older vers                                                                                   ions (hapi.im/commercial).
npm WARN deprecated sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as th                                                                                   is distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@5.2.0: This version has been deprecated in accordance with the hapi support p                                                                                   olicy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and                                                                                    security patches. If you are unable to upgrade at this time, paid support is available for older vers                                                                                   ions (hapi.im/commercial).
+ node-red-node-google@0.1.4
added 22 packages from 34 contributors and audited 1570 packages in 17.227s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-node-emoncms@0.2.1
added 1 package from 1 contributor and audited 1571 packages in 12.65s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-node-ping@0.1.0
added 1 package from 1 contributor and audited 1572 packages in 12.846s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-node-random@0.1.4
added 1 package from 1 contributor and audited 1573 packages in 12.87s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-node-smooth@0.1.2
added 1 package from 2 contributors and audited 1574 packages in 12.849s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-node-darksky@0.1.18
added 1 package from 1 contributor and audited 1575 packages in 12.946s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-influxdb@0.4.0
added 3 packages from 6 contributors and audited 1578 packages in 15.649s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-config@1.1.2
added 1 package from 1 contributor and audited 1579 packages in 12.72s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-grove@1.0.9
added 1 package from 1 contributor and audited 1580 packages in 14.564s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-diode@1.0.1
added 1 package from 1 contributor and audited 1581 packages in 12.936s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-bigtimer@2.2.5
added 2 packages from 2 contributors and audited 1583 packages in 14.463s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-esplogin@1.3.7
added 1 package from 1 contributor and audited 1585 packages in 13.069s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-timeout@1.1.4
added 1 package from 1 contributor and audited 1586 packages in 13.22s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-moment@3.0.3
added 24 packages from 9 contributors and audited 1621 packages in 17.463s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by defaul                                                                         t, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This no                                                                         tice will go away with v5.0.2+ once it is released.

> core-js@2.6.10 postinstall /usr/src/node-red/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ node-red-contrib-particle@1.1.0
added 13 packages from 22 contributors in 31.433s
+ node-red-contrib-web-worldmap@2.1.4
added 14 packages from 19 contributors and audited 1819 packages in 21.177s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-isonline@1.1.15
added 2 packages from 2 contributors and audited 1821 packages in 14.828s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-npm@1.0.2
added 433 packages from 845 contributors and audited 13808 packages in 42.328s
found 24 vulnerabilities (1 low, 23 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-file-function@1.1.2
added 1 package from 1 contributor and audited 13809 packages in 24.462s
found 24 vulnerabilities (1 low, 23 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-boolean-logic@0.0.3
added 1 package from 1 contributor and audited 13810 packages in 24.221s
found 24 vulnerabilities (1 low, 23 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-blynk-ws@1.0.1
added 4 packages from 5 contributors and audited 13822 packages in 27.912s
found 25 vulnerabilities (1 low, 24 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-owntracks@0.0.2
added 3 packages from 3 contributors and audited 13825 packages in 27.031s
found 25 vulnerabilities (1 low, 24 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container d40bf44e3aa7
 ---> a836c509eefe

Hope it hellps

**Comment by gcgarner** [comment]
Hi that is completely normal behaviour. Peter's scripts has the exact same output.
When you install that within Node-RED itself they hide all the errors. I will look into a way to suppress some of those warnings

**Comment by Paulf007** [comment]
Thank you Graham. 
I'll Close as this then normal behavior.
