### ISSUE TITLE
Python3 container build failed

### ISSUE THREAD

**Issue by LyJantos** [gcgarner/IOTstack#124]
Building the Python3 container failed with ...

```
Building python
Step 1/5 : FROM python:3
 ---> d73d859bc8fb
Step 2/5 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 3da7103bdf4e
Step 3/5 : COPY requirements.txt ./
ERROR: Service 'python' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder929464334/requirements.txt: no such file or directory
```

**Comment by kbloxsom** [comment]
I had the same problem. In the WIKI, it explains that you need to edit (create)
services/python/requirements.txt and add the two lines:
flask
bs4

Then save the file and go back and start the stack by navigating to the project folder containing the docker-compose.yml file: cd ~/IOTstack
To start the stack run: docker-compose up -d or ./scripts/start.sh

**Comment by LyJantos** [comment]
Thx!
