### ISSUE TITLE
Feature request: nginx reverse Proxy 

### ISSUE THREAD

**Issue by echtelerp** [gcgarner/IOTstack#15]
Hi gcgarner, 

thanks a lot for creating the project. I found found it on youtube - the guy with the swiss accent. :-) 
one nice option would be proxying all the services, to make them reachable via {url}/grafana, {url}/nodered, ... 
one possible source of inspiration could be from: 
https://github.com/janvda/balena-node-red-mqtt-nginx-TIG-stack

have a great day 
echteler

**Comment by gcgarner** [comment]
Hi Echteler

I've done some testing using linuxserver/letsencrypt with some success on nodered, just couldn't get the websockets up upgrade correctly to work with the debugging.  I'll add it to #14

**Comment by echtelerp** [comment]
I could help on that one, :-) 
just let me know. 
you need to add in the docker settings.js file: 
`httpRoot: '/nodered',
httpNodeCors: {
        origin: "*",
        methods: "GET,PUT,POST,DELETE"
         },`

in the grafana.ini:
`[server]
# Protocol (http, https, socket)
;protocol = http

# The ip address to bind to, empty will bind to all interfaces
;http_addr =

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain =  {dnsurl}.org

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
;enforce_domain = false

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = http:// {dnsurl}.org/grafana`


then the iginx.conf: 
`
events {}
http {
  server {
    server_name {dnsurl}.org;
    listen 80;
    root /usr/share/nginx/www;
    index index.html index.htm;
    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      #proxy_http_version 1.1;
      #proxy_set_header Upgrade $http_upgrade;
      #proxy_set_header Connection "upgrade";  
      proxy_pass http://webserver:80/;
    }
    location /nodered/ {
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_pass http://nodered:1880;
    }
    location /influxdb/ {
      proxy_pass http://influxdb:8086/;
    }
    location /grafana/ {
      proxy_pass http://grafana:3000/;
    }
}
´
each /servicename:port needs to be adjusted towards the service name of course.

**Comment by gcgarner** [comment]
I would really appreciate the help, I'm going to have to setup a wiki for the https section. When it comes to opening ports out to the web I want to make sure people follow safe practices. I would like to add some instructions for an ssh [tarpit](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=2ahUKEwirtdfm0L7lAhX5UhUIHbx4ClEQwqsBMAN6BAgJEAQ&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DqPEA6J9pjG8&usg=AOvVaw0CZxSSnelIWmyatquweJHX) or at least a link. I want to make some headway with the other requests first though.

i think i missed this: `httpRoot: '/nodered', httpNodeCors: { origin: "*", methods: "GET,PUT,POST,DELETE" }` in settings.js none of the write-ups i found mentioned that

**Comment by echtelerp** [comment]
I had to find all of this out by trial and error :-) 
took me about a week. 
If you like to I can push that on a repo. so far it is inside a private one, due to some specific configs like vpn keys and stuff...

**Comment by gcgarner** [comment]
Antonio is busy working on polishing the nodered Dockerfile to get SQLite and serial working. So i would hold off on that for now.

Which image did you use for the nginx proxy, letsencryt? I could always make a branch for testing

**Comment by gcgarner** [comment]
Hi Philipp I tried adding 

> httpRoot: '/nodered', httpNodeCors: { origin: "*", methods: "GET,PUT,POST,DELETE" }

into the settings.js file as you suggested but what happened was my nodered just  moved to nodered:1880/nodered and i had to change 

> proxy_pass http://nodered:1880/nodered/; }

this still didn't fix the issue that the websockets don't upgrade to wss so none of the debugging works. Do your debug nodes work with your reverse proxy?

I tested that with linuxserver/letsencrypt but i think i should just use straight nxinx

**Comment by gcgarner** [comment]
it could be a letsencrypt container issue and i need to set something else

**Comment by gcgarner** [comment]
Sigh, i have been chasing ghosts. My NAT reflection is the problem. The websockets works fine from the internet but not when I use the domain name from my internal network.

**Comment by gcgarner** [comment]
I've been doing some work on the reverse-proxy and i've hit a little stumbling block. Home assistant does not support being referenced via a subfolder `{url}/hassio` does not like it. I've only been able to get it working by subdomain. How would you, via an IP address, get a subdomain?

**Comment by echtelerp** [comment]
Hi gcgarner, 
sorry, I have not been online for a couple of days. 
so far i have not tried home assistant. so no info to that so far :-)
the thing with the debug node is solved i guess. otherwise, it all worked fine for me.

**Comment by echtelerp** [comment]
From what google says, reverse proxy and Ip adresses with subdomains are not possible, except when you edit the hosts file something ....

**Comment by gcgarner** [comment]
will be added in #14
