### ISSUE TITLE
influxdb add admin auth

### ISSUE THREAD

**Issue by echtelerp** [gcgarner/IOTstack#16]
would be adding the admin auth to influx make sense? 
you could add this to the env file for influx... 

      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminPW

**Comment by gcgarner** [comment]
I think it would. What i can do is put all the environmental variables in that exist and put comments in front of them. That way the user can decide on what they need depending on their needs.

**Comment by gcgarner** [comment]
I've added the remainder of the environmental variables listed on influxdb's docker hub page. Would you recommend enabling HTTP_AUTH by default?

**Comment by echtelerp** [comment]
I have it by default. so nobody can change my Indlux db if breached. :-)

**Comment by echtelerp** [comment]
actually i do this within a compose file. 
`influxdb:
    restart: unless-stopped
    image: echteler/influxdb:arm32v7
    container_name: influxdb
    environment:
      INFLUXDB_DB: dbhome
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: echtelerp
      INFLUXDB_ADMIN_PASSWORD: PhEc103900@
      INFLUXDB_USER: echteler
      INFLUXDB_USER_PASSWORD: Pe103900!
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - /media/usb01/dockerVolumes/influx:/var/lib/influxdb
    networks: 
      - edge`

**Comment by gcgarner** [comment]
Adding security suggestions to wiki
