### ISSUE TITLE
docker-compose build freezed or "killed"

### ISSUE THREAD

**Issue by ctrlce** [gcgarner/IOTstack#166]
Hi,

while trying to follow the install instruction on my Pi 3+ ver. A (2018), I have faced a 2 major problems.

1. I can install docker
2. While running `docker-compose up -d`, I cant pass through that step, as my Pi freezes (I tried to wait 2+ hours), or shows me the info attached below:

> pi@raspberrypi:~/IOTstack $ docker-compose up -d
Creating network "iotstack_default" with the default driver
Pulling portainer (portainer/portainer:)...
latest: Pulling from portainer/portainer
d1e017099d17: Pull complete
860ebb866910: Pull complete
Digest: sha256:4ae7f14330b56ffc8728e63d355bc4bc7381417fa45ba0597e5dd32682901080
Status: Downloaded newer image for portainer/portainer:latest
Pulling influxdb (influxdb:latest)...
latest: Pulling from library/influxdb
2478a2ed882c: Pull complete
2c541086e0df: Pull complete
edf0f97b070f: Pull complete
5f3fec049329: Pull complete
30fb79c48843: Pull complete
0159758a3df4: Pull complete
c1ccca322b77: Pull complete
87d1adef6dc1: Pull complete
Digest: sha256:571dbeeaeda64db869081b34a2717bef7b91bbeb9fff6988fc56df0a17e33e5c
Status: Downloaded newer image for influxdb:latest
Pulling grafana (grafana/grafana:6.3.6)...
6.3.6: Pulling from grafana/grafana
245dbad35e84: Pull complete
bc1d94e06384: Pull complete
1578a1c7d8ec: Pull complete
d5d560aa8fbb: Pull complete
525bba436572: Pull complete
b5d3581c6846: Pull complete
11664e74e734: Pull complete
2b25cb5ab71f: Pull complete
70952cf6efd0: Pull complete
Digest: sha256:218ba67bfac261a71abde7cb306727edaa7d9a595bd70ceb5a644ea3dfb21229
Status: Downloaded newer image for grafana/grafana:6.3.6
Pulling mosquitto (eclipse-mosquitto:)...
latest: Pulling from library/eclipse-mosquitto
e99479a55eec: Pull complete
91ee460ec80a: Pull complete
db79113e1248: Pull complete
Digest: sha256:e23c896ddc3dfb0cd67fb08be09c4ac9acc9adcbaeb5c0b1097d46679e84ac3e
Status: Downloaded newer image for eclipse-mosquitto:latest
Pulling pihole (pihole/pihole:latest)...
latest: Pulling from pihole/pihole
a737175813b0: Pull complete
2625d5ea6d14: Pull complete
94507c041947: Pull complete
96a14bd24362: Pull complete
33b32723995f: Pull complete
72c707fd0e20: Pull complete
b1625669ed53: Pull complete
0e0149908a0e: Pull complete
Digest: sha256:8c172c4cf344232a137202811b0c13a0542551076798d7635ef5368f40d1fe71
Status: Downloaded newer image for pihole/pihole:latest
Creating portainer ...
Creating grafana   ...
Creating influxdb  ...
Creating pihole    ...
Creating mosquitto ...
Creating nodered   ...
Killed

Could you please help me with that? I am struggling with it my second day. I am on a very begginig of my adventure with Raspberry Pi so I will appreciate any help, especially if I'm doing some rookie mistake.

Many thanks

**Comment by Paraphraser** [comment]
I have installed IOTstack on a 3B+. It worked without incident but it was in November last year using the then current Raspbian base. Whether what you are seeing can be explained by the RAM difference (512MB vs 1GB) or, assuming you’ve started from the current image, something that has changed between then and now is unknown.

Perhaps try starting it up like this:

```
$ docker-compose --verbose --log-level DEBUG up -d
```

You might get a hint from the additional output.

**Comment by ctrlce** [comment]
Unfortunatelly it didn't helped anything. But I think that the issue could be with lack of operational memory as on other forums I found similar reports solved as lack of ram. Also I just upgraded to newer  raspi 4 and it worked smoothly. 

Many thanks for your help though!
