### ISSUE TITLE
Hass.io installer link is broken

### ISSUE THREAD

**Issue by ei23-fxg** [gcgarner/IOTstack#171]
Hey!
The Hass.io link is not found.
Did they move it?
Is it now https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh
?

**Comment by robthepyro** [comment]
Looks like it
I'm trying manual install with that link now

**Comment by Urzzzala** [comment]
https://github.com/gcgarner/IOTstack/issues/165

**Comment by ei23-fxg** [comment]
Install with docker-compose.yaml works like this:

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - ./volumes/homeassistant/config:/config
    environment:
      - "TZ=Europe/Berlin"
