### ISSUE TITLE
Feature Request - Containers - Homebridge

### ISSUE THREAD

**Issue by macadamer** [gcgarner/IOTstack#18]
Apple Siri server https://github.com/nfarina/homebridge (Docker image at https://github.com/marcoraddatz/homebridge-docker which I haven't tested).

**Comment by gcgarner** [comment]
The docker image doesn't appear to be available for the armhf architecture. Docker hub only lists it as am64 and when I pull the image it fails. I will contact the maintainer and find out if they can make it manifest for armhf. Going to add it to #14 as unavailable for now
