### ISSUE TITLE
How do i restore my influxdb from backup

### ISSUE THREAD

**Issue by Cooilleeneyder** [gcgarner/IOTstack#198]
Hi,

copying all the stuff from the backup into the directories didn´t do the trick :(
Any sugestions for a noob?

**Comment by Paraphraser** [comment]
Hi,

I know it's easy to get confused between gagarner/IOTstack (this repo) and [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack) (the forked repo which is currently "active" while we wait for Graham Garner to resurface) but it's probably better to ask questions on the fork.

That said, I solved this problem of restoring InfluxDB databases a while back. Your question prompted me to create a repo to document my scripts. Please see [Paraphraser/IOTstackBackup](https://github.com/Paraphraser/IOTstackBackup) and let me know if it was helpful.

**Comment by Paraphraser** [comment]
@Cooilleeneyder If your question has been answered, I'd appreciate it if you could remember to close this issue.
