### ISSUE TITLE
feature request airplay 

### ISSUE THREAD

**Issue by echtelerp** [gcgarner/IOTstack#20]
airplay:
    restart: unless-stopped
    image: echteler/shairport:arm32v7
    container_name: airplay
    environment:
      AIRPLAY_NAME: DockerOffice
    privileged: true
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - shairportConf:/etc
    network_mode: host

I always use self build images, based on alpine... the original is orbsmiv/shairport-sync-rpi

**Comment by gcgarner** [comment]
Hi Philipp I want to integrate this now, I just want to know a little more about it.
I went to the docker hub page and there wasnt much there.

some questions:
- could you provide a link to the git repo where the Dockerfile is stored, I see its not on your Github (will be helpful for people wanting to write their own Dockerfiles)
- could you point me to a resource where i can make a write-up on the container

**Comment by gcgarner** [comment]
Sorry, nevemind about the git repo ... if you look properly you find it [docker-environment](https://github.com/echtelerp/docker-environment/tree/master/base_images/arch_arm32v7/shairport)

**Comment by gcgarner** [comment]
another dumb question, this is obviously an Apple airplay application. Is this so you can play audio to the Pi? or does it have another purpose?

**Comment by echtelerp** [comment]
it is a possibility to use the PI as an Airplay reciver :-)
I have that in my office... my pi is vai a 3,5mm klinke connected to my stereo system :-)

**Comment by gcgarner** [comment]
added to #14
