### ISSUE TITLE
webthings_gateway image name changed

### ISSUE THREAD

**Issue by Set-Me-Up** [gcgarner/IOTstack#204]
Following error is beeing displayed:
ERROR: manifest for mozillaiot/gateway:arm not found: manifest unknown: manifest.

I fixed it by changing in the generated yml file the pulled image name:

name for Raspi is:
image: mozillaiot/gateway

no : arm is required.

**Comment by Slyke** [comment]
Please note that this repo is deprecated. Follow the instructions to switch to the new one: https://github.com/SensorsIot/IOTstack, which is still actively developed. Once switching, retry installing gateway again. I suspect they've updated their docker labels if it fails again.

**Comment by Paraphraser** [comment]
Slyke has given you good advice. Please see also [* * THIS PROJECT IS DORMANT * *](https://github.com/gcgarner/IOTstack/issues/194).

It is possible that your problem has been fixed on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack). In any case, you are more likely to get support if you migrate your installation to SensorsIot/IOTstack, find that your problem has not been fixed, and open another issue there.

If you have not already joined [the Discord channel](https://discord.gg/W45tD83), you can often get help there too.

I'd really appreciate it if you would close this issue on gcgarner/IOTstack:

* Recently opened issues give the impression that this repo is active - it isn't.
* A pile of ancient open issues with no responses give the impression that the IOTstack project has been abandoned - it hasn't been.

Forking the repo was the only possible way of continuing once Graham Garner "disappeared".

**Comment by Set-Me-Up** [comment]
I was actually looking for the SensorsIot IOTstack, this was the first hit google gave me and I didn't notice.
