### ISSUE TITLE
HASSIO not running port 8123

### ISSUE THREAD

**Issue by garlandkr** [gcgarner/IOTstack#205]
I used the menu to install HASSIO and all of the containers appear to be running, however the home-assistant container does not have any ports assigned. Only the observer shows a port being available and forwarded.

> homeassistant/armv7-hassio-multicast:3             "/init"                                                                                                        
> homeassistant/armv7-hassio-cli:26                  "/init /bin/bash -c …"
>homeassistant/armv7-hassio-audio:17                "/init"
>homeassistant/armv7-hassio-dns:9                   "/init coredns -conf…"
>homeassistant/raspberrypi4-homeassistant:0.115.2   "/init"
>homeassistant/armv7-hassio-observer:3              "/init"           0.0.0.0:4357->80/tcp                                                                        
>homeassistant/armv7-hassio-supervisor              "/init"

**Comment by Paraphraser** [comment]
Please see [* * THIS PROJECT IS DORMANT * *](https://github.com/gcgarner/IOTstack/issues/194).

It is possible that your problem has been fixed on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack). In any case, you are more likely to get support if you migrate your installation to SensorsIot/IOTstack, find that your problem has not been fixed, and open another issue there.

If you have not already joined [the Discord channel](https://discord.gg/W45tD83), you can often get help there too.

I'd really appreciate it if you would close this issue on gcgarner/IOTstack:

* Recently opened issues give the impression that this repo is active - it isn't.
* A pile of ancient open issues with no responses give the impression that the IOTstack project has been abandoned - it hasn't been.

Forking the repo was the only possible way of continuing once Graham Garner "disappeared".

**Comment by garlandkr** [comment]
oh well, I already moved on and removed IoTStack/Portainer. Easier to manually manage docker packages.

**Comment by garlandkr** [comment]
oh well, I already moved on and removed IoTStack/Portainer. Easier to manually manage docker packages.
