### ISSUE TITLE
Motioneye not running on RaspberryPi after minor edits to html templates and docker build

### ISSUE THREAD

**Issue by edsase** [gcgarner/IOTstack#206]
I followed the build instructions for building Motioneye from a Docker image. After cloning the Github repo, I did some edits to the html templates before running docker build command. However, running the container image does not work as expected. The usual initial login modal doesn't pop up but rather, I get directly to the main page. The menu on the main page is not working and so there is nothing I could do on that page. On the other hand, when I clone the repo and build the image without first editing the html templates, I don't get any issues. Could it be that for the docker install the html templates should not be edited? Thanks already for your responses!

**Comment by Paraphraser** [comment]
Please see [* * THIS PROJECT IS DORMANT * *](https://github.com/gcgarner/IOTstack/issues/194).

It is possible that your problem has been fixed on [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack). In any case, you are more likely to get support if you migrate your installation to SensorsIot/IOTstack, find that your problem has not been fixed, and open another issue there.

If you have not already joined [the Discord channel](https://discord.gg/W45tD83), you can often get help there too.

I'd really appreciate it if you would close this issue on gcgarner/IOTstack:

* Recently opened issues give the impression that this repo is active - it isn't.
* A pile of ancient open issues with no responses give the impression that the IOTstack project has been abandoned - it hasn't been.

Forking the repo was the only possible way of continuing once Graham Garner "disappeared".

**Comment by edsase** [comment]
Thanks for the tips @Paraphraser . Will move this issue to other channels.
