### ISSUE TITLE
New Feature request: jlesage/firefox

### ISSUE THREAD

**Issue by TonyPeperoni** [gcgarner/IOTstack#222]
The docker image jlesage/firefox makes it possible to access HASS.io through a modern browser via outdated tablets. Thus giving older iPad models a second life as central screens for HASS. To me this seems like a nice and quick win addition to the IOTstack. What are your thoughts? regards, Ton

**Comment by Paraphraser** [comment]
Hi - please see [this project is dormant](https://github.com/gcgarner/IOTstack/issues/194).

Sounds like a reasonable idea. The best way to get things added is to prepare a Pull Request.

**Comment by TonyPeperoni** [comment]
Thank you I will follow up

**Comment by TonyPeperoni** [comment]
@Paraphraser I could not figure out how to create a pull request. I got a bit lost there.

**Comment by Paraphraser** [comment]
My mistake. I probably intended to give you [this link](https://gist.github.com/Paraphraser/818bf54faf5d3b3ed08d16281f32297d) but forgot.
