### ISSUE TITLE
which Home Assistant installation should I use

### ISSUE THREAD

**Issue by bub4** [gcgarner/IOTstack#225]
Hi Graham,

Thank you for IOTstack. This project makes me brave enough to try docker and home assistant. 
But which version shall I install? The native installation of hass.io or the home assistant listed in the stack?

I tried the one to chose in the stack menu - not the one in native install - and it worked out, but the wiki sais following:

_Hass.io now has a seperate installation in the menu. The old version was incorrect and should be removed. Be sure to update you project and install the correct version.

You will be asked to select you device type during the installation. Hass.io is no longer dependant on the IOTstack, it has its own service for maintaining its uptime.__

Cheers

**Comment by Paraphraser** [comment]
Please see [This Project Is Dormant](https://github.com/gcgarner/IOTstack/issues/194).

I don't run hass.io or anything like it so I can't say whether the SensorsIot fork of this repository deals with the problem you are raising but I'm pretty sure I've seen discussions like this over there. There's also a Discord channel (you'll find the link at the other repo) where you can ask questions like this.

Please try to remember to close this issue.

**Comment by bub4** [comment]
Thank you very much, Phill.

Take care
