### ISSUE TITLE
InfluxDb data not in backup

### ISSUE THREAD

**Issue by dmenne** [gcgarner/IOTstack#229]
When I tried to recover data from a backup today, I noted that the folder from InfluxDb was empty. Is this a limitation because of locked files, or did I installs something incorrectly?

**Comment by dmenne** [comment]
Sorry, RTFM. Influxdb has separate backups. Mea Culpa, Closing

**Comment by Paraphraser** [comment]
Something else you might want to read is [This Project is Dormant](https://github.com/gcgarner/IOTstack/issues/194).

If you decide to upgrade to the new repo, you could also take a look at [Paraphraser/IOTstackBackup](https://github.com/Paraphraser/IOTstackBackup). Definitely handles InfluxDB!

**Comment by dmenne** [comment]
Thanks, I had seen IOTstackBackup, but had not realized that GC has disappeared in virtual space.
