### ISSUE TITLE
Z-wave container #Add-on

### ISSUE THREAD

**Issue by misujr** [gcgarner/IOTstack#23]
Awesome work with this project ! Absolutely great way to help people start using containers. 
It is my first time working with containers and it is just great !
I have a little project that I have built based on influxdb, grafana and Zwave. 
I am trying to learn how to build a container for Zwave for Raspberry but it is a lot of information out there that does not help to understand how to tailor the image build for arm processors and also I have no idea what base image should I put.  Is there any guide you have followed to make this images you have included in this git ? If so, can you share it ? I would be happy to try and put together a Z-wave container that will work in this project as I am sure there will be may out there needing it .

BR,
Misujr

**Comment by gcgarner** [comment]
Hi Misujr
It would be great if you can contribute. We have just setup a discord to assist collaboration, check the readme for the link. 

As for the base image, it depends on what you need "pre-installed" with the image like nodejs etc. You could start off with a an debian image and install node or just base everything on the node image. I find it very helpful to read other peoples Dockerfiles. Have a look at nodered's [Dockerfile](https://github.com/node-red/node-red-docker/blob/master/docker-custom/Dockerfile.custom). They have based the image on alpine which is a smaller image. You don't need to use all the fancy switches. [Grafana Dockerfile](https://github.com/grafana/grafana-docker/blob/master/Dockerfile) uses debian slim.

Depending on the community needs we may setup a Wiki page on how to add to the project with a starters guide as you suggest.

**Comment by gcgarner** [comment]
Adding Z-wave to wishlist in #14
