### ISSUE TITLE
menu.sh just checks for current version

### ISSUE THREAD

**Issue by BernH4** [gcgarner/IOTstack#233]
When i run ./menu.sh i get this output:

```
~/IOTstack ~/IOTstack
checking for project update
From https://github.com/gcgarner/IOTstack
 * branch            master     -> FETCH_HEAD
Project is up to date
~/IOTstack
```

And it exits afterwards. Let me know if i can help more solving this issue.

**Comment by Paraphraser** [comment]
Please see [This project is dormant](https://github.com/gcgarner/IOTstack/issues/194).

Please try to remember to close this issue.

**Comment by Slyke** [comment]
It will exit if you select `Yes` from the prompt. Selecting `No` will allow you to continue using the menu, and it won't prompt you again about it being dormant.
