### ISSUE TITLE
Wish List - Add Lamp Server

### ISSUE THREAD

**Issue by Paulf007** [gcgarner/IOTstack#24]
Consider Adding a Lampserver or alternative as default. 
One could then have a Default page with all the Docker Apps Links on it as they are installed.

**Comment by gcgarner** [comment]
Hi Paul, I saw your comments n  #21 and my "static domain_name_servers" is blank.

however running this yeilds
```
$ grep "nameserver" /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

it would appear that PiVPN stores the dns in another file.

The lamp stack is on the wishlist
