### ISSUE TITLE
Difficulty adding passwords to mosquitto container

### ISSUE THREAD

**Issue by alfb113** [gcgarner/IOTstack#32]
It may be my finger trouble but I followed the instructions to generate and activate a user/password combo for mosquitto and had difficulty after enabling.
The helper instructions "mosquitto_passwd -c /mosquitto/config/passwd MYUSER" put the new password file in passwd
BUT the last line in mosquitto.conf pointed to pwfile
I suspect the helper instruction should have been "mosquitto_passwd -c /mosquitto/config/pwfile MYUSER"

**Comment by gcgarner** [comment]
Thank you, you are 100% correct making that changes now
