### ISSUE TITLE
Node Red install error 139

### ISSUE THREAD

**Issue by paul-b-63** [gcgarner/IOTstack#37]
I have attempted to install this stack and I can not get past this one section.

New install of Raspbian Buster Lite as I figure I don't need the GUI.
pulled the Stack and followed the directions.

I get this:
```
pi@raspberrypi:~/IOTstack $ ./menu.sh 
Adding portainer container
Adding Node-RED container
Adding influxdb container
Adding Grafana
Adding Mosquitto
docker-compose successfully created
run \'docker-compose up -d\' to start the stack
pi@raspberrypi:~/IOTstack $ docker-compose up -d
Building nodered
Step 1/2 : FROM nodered/node-red:latest
 ---> b04b04ad7675
Step 2/2 : RUN for addonnodes in node-red-node-pi-gpiod node-red-dashboard node-red-node-ping node-red-contrib-influxdb ; do npm install ${addonnodes} ;done;
 ---> Running in 537f7080658e
ERROR: Service 'nodered' failed to build: The command '/bin/sh -c for addonnodes in node-red-node-pi-gpiod node-red-dashboard node-red-node-ping node-red-contrib-influxdb ; do npm install ${addonnodes} ;done;' returned a non-zero code: 139
pi@raspberrypi:~/IOTstack $ 
```

-
If I copy the offending line and remove the '/bin/sh -c'  it seems to work, but that does not get me past the docker-compose up command.

I did have to install npm prior to this as it was not in the initial OS load.
Are there dependencies missing that we are not aware of or am I doing something silly?

**Comment by gcgarner** [comment]
Hi Paul, I'll have a look, I havent seen that error in testing.
That command `/bin/sh .....` is running in the container not on your host system. 

I just deleted all my containers and images and build the same configuration as you and my build was successful.

Which Raspberry Pi are you using? do you have enough disk space run `df -h`
you can force a rebuild by running `docker-compose build nodered` and see if the error persists

**Comment by paul-b-63** [comment]
Hi Graham,  thank you got your reply, and thank you for putting this together.  I had no idea on docker , or some of the applications, until I saw Andreas video.  If I can get this to work I will attempt to take it apart and figure out how it works..  :)

There is space on the device:
pi@raspberrypi:~/IOTstack $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.1G  2.2G  4.6G  33% /
devtmpfs        213M     0  213M   0% /dev
tmpfs           217M     0  217M   0% /dev/shm
tmpfs           217M  3.2M  214M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           217M     0  217M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   52M  201M  21% /boot
tmpfs            44M     0   44M   0% /run/user/1000
pi@raspberrypi:~/IOTstack $ 

which is why  I went for the Lite install.
I am using a B+ at the moment.  Did you have the same issue with having to install npm first? But you said the command is run from the container not the host...  The error, when run on the command line, is a syntax error. 

For testing and maybe a little usage, I would have thought the B+ would work, albeit slow when under load.
I have literally just received a Pi 3 B in the mail and will try that with a 16Gb SD card.
I will try both the base install, to see if it is my environment, and a full NOOBS install.

**Comment by gcgarner** [comment]
The video was a little light on the in-depth info on docker. The plan is to setup a project wiki that explains the basic concepts ... like your container cant see the host file system for one.

Are you using a model 1B+ or a different B+? The model 1 wont run because it has a different CPU version. The best is to use the 3B, I just tested the above install and it did work on my 3B

If you want to use the 1B you are best off using Peter Scargill's script, there is a like on the README

**Comment by paul-b-63** [comment]
I just moved the 8Gb SD card to the Pi 3 B and it runs past that point and installs.
It seems the other containers may work on the B+ just not Node Red, I didn't test them, just there were no errors when Node Red was deselected.  I would not have said this was a hardware issue.
Mine is a v1.2 B+.
I would have thought an ARM is an ARM and the OS would be a common layer on top, but Live and learn. 
I will ask if you can put something on the readme to suggest the Pi model limitations. 
Thank you for jumping on this.  I think it is now resolved :)

**Comment by gcgarner** [comment]
I've updated the README now. Things get complicated with ARM, there is armv5,armv6,armv7,armhf, arm64. Its hard to keep track. I will look into how to put an error in the menu itself
