### ISSUE TITLE
Configurator, install and activate

### ISSUE THREAD

**Issue by jiminbayble** [gcgarner/IOTstack#41]
Having trouble installing and activating configurator with the docker set up.

**Comment by gcgarner** [comment]
I don't understand what you are referring to. Could you be more specific?

**Comment by gcgarner** [comment]
i assume you are refering to Home assistant Configurator

see the following writeup https://www.home-assistant.io/docs/configuration/

to enter the terminal for home assistant type the following
`docker exec -it hassio /bin/bash`

you are now in the hassio terminal

run 
`wget https://raw.githubusercontent.com/danielperna84/hass-configurator/master/configurator.py`
then
`python configurator.py` 
port 3218 will now be open, navigate to your_ip:3128 in your web browser for the configurator

the writeup also says how you can add it to you home assistant

**Comment by gcgarner** [comment]
It appears that the whole home assistant is configured incorrectly from my side, It should be revised in the next few days

**Comment by jiminbayble** [comment]
I'll leave off fiddling with my setup for a few days then, cheers.

Jim

**Comment by gcgarner** [comment]
I've added the now corrected Hass.io
