### ISSUE TITLE
username/password

### ISSUE THREAD

**Issue by jiminbayble** [gcgarner/IOTstack#42]
When I try to access my ha page at 192.168.1.53:8123 from a different pc or phone, I'm asked for a user name and password. IThere is no option to set up user name/ password when installing via docker, so I asssume these must have hard coded in the container?

**Comment by jiminbayble** [comment]
Also unable to access ha from a different browser on same pc.

**Comment by gcgarner** [comment]
The first time you start up HA and navigate to <yourip>:8123 you are asked to create a username and password. It should ask you for that username and password when you attempt to open that page from any other computer. (I didnt realise this first time myself)

If you have forgotten it you will have to delete the home assistant volume and start over home assistant from scratch
```
docker-compose down
sudo rm -r /home/pi/IOTstack/volumes/hassio/
docker-compose up -d
```

![image](https://user-images.githubusercontent.com/46672225/68215514-0ef5dc00-ffe8-11e9-878d-ca1b58d0a16c.png)

**Comment by jiminbayble** [comment]
Thats sorted it.
Thanks
