### ISSUE TITLE
Raspbian lite - pigpiod not accessible from node-red container

### ISSUE THREAD

**Issue by craigh1015** [gcgarner/IOTstack#43]
I installed pigpiod and started it up. By default it starts locally and the node-red container cannot see port 8888 of the PI. If I change the startup to global (-g) pigpiod fails to start.

**Comment by gcgarner** [comment]
Which version of rasbian are you using? If you installed it then i assume you are using rasbian lite

https://github.com/gcgarner/IOTstack/wiki/Node-RED#gpio Did the method described here not work for you?

**Comment by gcgarner** [comment]
I just started a brand new Raspian Lite, installed the pigpio as described, added the rc.local (rebooted) and mine works. My IP is 192.168.88.81 

were you running it from the CLI?

![image](https://user-images.githubusercontent.com/46672225/68218792-8ed27500-ffed-11e9-8b32-507a58b3d3cf.png)

**Comment by craigh1015** [comment]
I am running 2019-07-10 rasbian buster lite.

I was originally trying to run pigpiod through systemctl - I have disabled that now.

I made the change to /etc/rc.local after reboot I see pigpiod is running (vi ps) however it crashes.

I have now been successful running `sudo pigpiod &`

I am not sure why this is able to keep running - it will not survive a restart - but at least I can now proceed

**Comment by gcgarner** [comment]
Roughly how long does it take before it starts to crash?
Is it after you take any specific action? I would like to see if i can reproduce your results
after running `sudo pigpiod &` in the background does it bomb out at all?
for me running `sudo systemctl status` yeilds:
![image](https://user-images.githubusercontent.com/46672225/68242866-f9010f00-0019-11ea-9b8b-f3ccd8c13c02.png)
do you maybe have duplicates `sudo systemctl status | grep "gpio"` other that the grep

**Comment by craigh1015** [comment]
Using the default systemctl config pigpiod gets started with "-l" flag.
NodeRed then gives an "UNREACHABLE" error.

When I edit the installed pigpiod.service file or create a new one so I can start with "-g" flag then
`systemctl start pigpiod` fails to complete

I have now run into a new issue with the pi3 reading a DS18B20 temp sensor over 1wire so  am going to start everything from scratch later this week or over the weekend.

**Comment by craigh1015** [comment]
I have been able to get my DS18B20's connected to node-red and did some further testing with the pigpio.

I have `/usr/bin/pigpiod` in `/etc/rc.local` after a reboot everything work fine initially then after a couple of minutes pigpio crashes and I get the following error in `/dev/pigerr`
2019-11-09 07:03:59 sigHandler: Unhandled signal 18, terminating

I do not appear to get this error if I run `sudo pigpiod &` after boot

**Comment by gcgarner** [comment]
I'm going to see if i can replicate on my spare 3B, on rasbian lite. Did you get the ds18b20 working in your docker version of nodered, if so which node did you use?

**Comment by gcgarner** [comment]
Test a 18b20 with `node-red-contrib-ds18b20-sensor` and it works fine on my 3b running docker. now to test the lite with your gpio issues

**Comment by craigh1015** [comment]
I am using node-red-contrib-ds18b20-sensor v1.3.6 for temp sensor. It is happily reading 3 sensors.

pigpio started from command line `sudo pigpiod &` appears to continue to be running fine.

**Comment by gcgarner** [comment]
Last night i setup a new Raspbian lite image on a 3B. Set it up and followed the rc.local method for getting the gpio working. So far I've had 10 hours of uptime on the GPIO without a crash.

I'm going to see what happens if I mess around with it's service so see if I can break and repair the pigpiod

**Comment by craigh1015** [comment]
My architecture has changed and I am now running my temp sensors on some remote ESP8266 boards.

I no longer have any pin usage on the pi.

Closing the issue as I am no longer effected by it.
