### ISSUE TITLE
Huge number of compiler warnings for SQLite

### ISSUE THREAD

**Issue by Paraphraser** [gcgarner/IOTstack#44]
I have run into a large number of compiler warnings (~3800 lines) which appear to be related to my decision to install node-red-node-sqlite via ./menu.sh

Initially I thought it might be related to my starting point ("Raspbian Buster with desktop" 2019-09-26) not having sqlite3 installed by default so I blew everything away and started over from scratch, including a:
```
sudo apt-get install sqlite3
```
along the way but I got the same long list of compiler warnings.

A test flow using the sqlite node definitely works so these warnings may be no more than an irritation. I'm only raising this issue to document the problem in case you have not been seeing the same thing in your testing.

I have not tried starting over but omitting node-red-node-sqlite at the ./menu.sh stage, then adding it later via Node-Red's "Manage Palette" command.

For the record, I'm using a brand new RPi4B with 4GB, booting from a 16GB SD card but running from a 440GB USB-3 SSD. The Pi is running "headless". The only other "add-on" prior to starting the Docker install is the VNC service.

[SecondInstallSQLiteWarnings.txt.zip](https://github.com/gcgarner/IOTstack/files/3813397/SecondInstallSQLiteWarnings.txt.zip)

**Comment by gcgarner** [comment]
Hi, yes this is completely normal unfortunately. There isnt a way to suppress the those errors.

If you try to add the node later it will fail. It needs to be installed with "--unsafe" from a command line

**Comment by gcgarner** [comment]
I did leave a note in the documentation, I just made it bold :)

**Comment by Paraphraser** [comment]
OK. Noted. Thanks.

And, a truly *excellent* idea you’ve had here with this Docker project.

I’ll also add a +1 vote for PiHole.
