### ISSUE TITLE
[Question] Tip for adding custom images?

### ISSUE THREAD

**Issue by BlackMix** [gcgarner/IOTstack#46]
Could you explain how to add custom images to your project?
maybe looking at your files I can do that but it would be nice to have your wiki form for people to add more options.
I wanted to add Plex and Pi Hole.

Thanks

**Comment by BlackMix** [comment]
oh, I got it, I added pi-hole and plex server.
thanks for good work!

**Comment by gcgarner** [comment]
... glad i could help ...
Pi-hole should be added in my next update tomorrow. I'm curious what you did with your port assignments, port 80 and 8080 are in short supply
For Plex did you mount an external drive?

**Comment by BlackMix** [comment]
Plex uses port 32400 for web views, worked fine.
I used this https://github.com/linuxserver/docker-plex for add

**Comment by gcgarner** [comment]
I've added Pi-hole to the stack, in the next week I'll possibly add plex. First i have to prepare some entries on how to add external drives to your fstab
