### ISSUE TITLE
Node-Red ... missing Input  / Output on my palette

### ISSUE THREAD

**Issue by dmurphydrtc** [gcgarner/IOTstack#47]

**Comment by dmurphydrtc** [comment]
First.. thanks for the great work. much appreciated.

Really basic issue but doing my head in...

I'm missing Input and Output from palette but have all the others eg Common, Function, Network.

what have i missed?

**Comment by Slyke** [comment]
Is there an npm module that needs to be installed, if so what is it? I can add it to the list of modules installable by node red and submit a PR for it.

**Comment by dmurphydrtc** [comment]
Alas I'm not sure what the module is.

**Comment by dmurphydrtc** [comment]
I'm hoping more informed heads will prevail

**Comment by gcgarner** [comment]
I had a look at the my interface vs some other that is saw on the web via a google image search

It would appear that the nodes have been grouped under "common" and "network":
![image](https://user-images.githubusercontent.com/46672225/68385571-c0b91800-0162-11ea-998d-9475a37d46c6.png)
my window:
![image](https://user-images.githubusercontent.com/46672225/68385636-e2b29a80-0162-11ea-929b-2c5d8c8f8de7.png)

**Comment by dmurphydrtc** [comment]
Ta for the reply.....but why are we missing input and output...which is the starting point of putting flows together.

**Comment by gcgarner** [comment]
Have a look at the pictures i send, the bottom one is my as installed node red. The input and output nodes are grouped together under "common" and "network"

do you see that the inject, debug etc nodes are all there?

**Comment by dmurphydrtc** [comment]
Apologies..all sorted.thanks again.

**Comment by dmurphydrtc** [comment]
Graham...or other learned friends...msg.payload / serial nodes are missing. Is there some node.js software module missing here?

**Comment by gcgarner** [comment]
@dmurphydrtc I haven't added the serial node yet. still working on the docker integration for it

**Comment by dmurphydrtc** [comment]
OK...understood and working fine.
