### ISSUE TITLE
Accessing Mosquitto on IOTstack

### ISSUE THREAD

**Issue by xelectro** [gcgarner/IOTstack#48]
Hi I have installed and configured the stack with excellent results. All items seem to work I even set the password for mosquitto but I can’t seem to gain access to the interface.
Tried localhost:1883 and several other ports.
What am I missing to get into mosquitto
Thanks

**Comment by gcgarner** [comment]
Hello, as far as i am aware mosquitto doesn't have a web interface. port 1883 is for the mqtt traffic itself. You can access the mosquitto terminal via the script `./services/mosquitto/terminal.sh` (if run from the IOTstack folder). However you will only be able to run command line tools.

Typically you just need to run mosquitto and you will interface to it via Node-RED. The topics that you send from any mqtt client will be created in mosquitto automatically 

https://www.youtube.com/watch?v=AsDHEDbyLfg here is a video where he shows the mosquiito_pu and mosquitto_sub commands. the only difference is the they would need to be run inside the mosquitto terminal not in the regular terminal

side note, remember that if you are trying to talk to mosquitto from nodered that if you use the default config the address would be "mosquitto" but it you activate the network_mode=host then it will be "127.0.0.1"

**Comment by xelectro** [comment]
Thank you for such a quick response.
I was just a bit confused and assumed that mosquitto has its own web interface. So this means that my stack is working exactly as it’s supposed to thanks to your software.
Thanks
Anthony

**Comment by laenan8466** [comment]
Hey Graham,
thanks for your awesome IOT stack. 
I got stuck with the config address of the mosquitto server locally for two days now, finally finding this very helpful issue.
Suggestion: Please add the information about network_mode to the Wiki entries of MQTT and/or node-red. This information was really hard to find, as a newbie to Docker and IOTstack.  I guess changes in the Wiki aren't possible for every github user?
Cheers, Laenan

**Comment by gcgarner** [comment]
Thanks, I will add it when i get home next week.

I really wish github would allow PRs on the wiki
