### ISSUE TITLE
Request - Tasmoadmin

### ISSUE THREAD

**Issue by smadds** [gcgarner/IOTstack#51]
Could I please make a request for you to add Tasmoadmin (https://github.com/reloxx13/TasmoAdmin) as an optional container? I have tried the existing containers I can find for ARM but none seem to run for more than a few seconds on the Pi without stopping.

Thanks

**Comment by gcgarner** [comment]
I did a little searching and it appears that TamsoAdmin/SonWEB is available as an addon in hassio

I will have a look at the stand-alone container. Some of the containers have odd user/group settings and require some tweaking to get running

**Comment by smadds** [comment]
Thanks. I have just tried this: raymondmm/tasmoadmin:latest from Docker Hub and it seems to be stable on the Pi... so far!

**Comment by gcgarner** [comment]
I see that was already in the list in #14 will get to it next week
