### ISSUE TITLE
Incorrect timezone on containers 

### ISSUE THREAD

**Issue by ddean6232** [gcgarner/IOTstack#55]
seems to be set to UTC and not the host time.  host time correct when checked with $ date

**Comment by gcgarner** [comment]
I'll push an update next week that will set the time zones correctly for all containers

**Comment by gcgarner** [comment]
I'm not near a computer at the moment. Will post an interim solution later today

**Comment by gcgarner** [comment]
Sorry i forgot to get back to you on this

You can edit your ./services/nodered/nodered.env and add `TZ=America/New_York` or whatever your time-zone is . Run `cat /etc/timezone` in the terminal to find the correct format

Afterwards run `docker-compose up -d` and it should be fixed

**Comment by Paraphraser** [comment]
This was not working for me. I eventually traced it to there being no "env_file" entry in the nodered grouping in the YAML file. For the record, I did a "git pull" before doing all this.

1. Excerpt from **unedited** YAML file:

```
  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data
```

2. Test (TZ does **not** take effect):

```
$ cat ~/IOTstack/services/nodered/nodered.env 
TZ=Australia/Sydney

$ docker-compose up -d
nodered is up-to-date
influxdb is up-to-date
mosquitto is up-to-date
pihole is up-to-date
grafana is up-to-date
portainer is up-to-date

$ docker exec -it nodered bash
bash-4.4# date
Tue Nov 12 05:13:47 UTC 2019

```

3. Excerpt from **edited** YAML file:

```
  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    ports:
      - 1880:1880
    env_file:
      - ./services/nodered/nodered.env
    volumes:
      - ./volumes/nodered/data:/data
```

4. Test (TZ **does** take effect):

```
$ cat ~/IOTstack/services/nodered/nodered.env 
TZ=Australia/Sydney

$ docker-compose up -d
Recreating nodered ... 
mosquitto is up-to-date
grafana is up-to-date
portainer is up-to-date
pihole is up-to-date
Recreating nodered ... done

$ docker exec -it nodered bash
bash-4.4# date
Tue Nov 12 16:23:26 AEDT 2019
```

**Comment by gcgarner** [comment]
Thanks, I'm working on injecting all the time-zones into all the containers I added the env file to my version and forgot the original one does not have the file yet

**Comment by ddean6232** [comment]
Thanks @Paraphraser Phill.... worked like a charm

**Comment by gcgarner** [comment]
Time-zone has been added for nodered and pihole

If you have an existing nodered and/or pihole it requires you to select complete template from build menu
