### ISSUE TITLE
PiHole won't respond on port 8089

### ISSUE THREAD

**Issue by Paraphraser** [gcgarner/IOTstack#60]
Clean install (all the way from bare metal) on RPi4B 4GB completed at roughly 2019-11-22T10:15:00Z.

The following services seem to be working as expected:

- InfluxDB: from the RPi, I can connect to the daemon and create databases.
- Mosquitto: From another host I can send and receive MQTT messages to/from port 1883.
- Node-Red: From a browser on another host I can connect to port 1880.
- Portainer: From a browser on another host I can connect to port 9000.
- Grafana From a browser on another host I can connect to port 3000.

For PiHole:

- From a terminal session on another host I can use nslookup to direct queries to port 53 and receive expected responses.
- **BUT** from a browser on another host, trying to open an HTTP session on port 8089 produces:

```
[ERROR]: Unable to parse results from queryads.php: Unhandled error message (Invalid domain!)
```

I am running the RPi4B "headless" with VNC enabled. Within a VNC session, launching Chromium and probing the URL "http://127.0.0.1:8089/" produces the same result.

**Comment by Paraphraser** [comment]
I should probably add that during the build process, I used raspi-config to rename the RPi from the default "raspberrypi" to "iot-hub". The WiFi interface also gains a fixed IP address assigned by DHCP (the Ethernet interface is not yet physically connected).

From an external browser I have tried:

- http://iot-hub.local:8089/
- http://x.x.x.x:8089/

The result is always the same. "Unable to parse results..."

However, when I execute a "sudo reboot" immediately _after_ running raspi-config to rename the RPi, it produced this error:

```
sudo: unable to resolve host raspberrypi: Name or service not known
```

I have done several bare-metal installations and this error always occurs at this point. But for any given installation, this error is one-time. Reboots during the rest of the installation process do not complain.

I just find myself wondering if "Invalid domain" and "unable to resolve host raspberrypi" might be related and if, perhaps, the PiHole installation is expecting the name "raspberrypi"?

**Comment by gcgarner** [comment]
Can you try adding the subfolder /admin or /Admin to url the wiki has the details ? (on my mobile, will respond in detail regarding the name change when I'm home)

**Comment by Paraphraser** [comment]
Adding /admin works but I've been running PiHole on a dedicated RPi3B+ for about a year and I was looking at the behaviour of the Docker install from that perspective.

When I send a no-subfolder HTTP request to the RPi3B+, I get:

<img width="339" alt="Screen Shot 2019-11-10 at 22 55 06" src="https://user-images.githubusercontent.com/34226495/68543596-3b0cc500-040d-11ea-9a01-6e67ccd7ad92.png">

It was that difference in behaviour I was talking about. The reason I stepped through the other running containers was to make sure that the others responded "as expected" and that Docker/Pi-Hole's apparently atypical response to a no-subfolder URL couldn't be explained by that being typical of **any** service being run inside Docker.

I know that sounds convoluted but I hope my reasoning and explanation is clear.

**Comment by gcgarner** [comment]
I know when I was running pihole on my old pi it did the redirect for me, I'll check the settings when I'm home, maybe I misse a setting. I remember I pulled their github repo and executed it from there

**Comment by gcgarner** [comment]
I want to setup a reverse proxy so you can access each service straight from port 80 with the correct sub folder
