### ISSUE TITLE
dropbox reinsert access token

### ISSUE THREAD

**Issue by gajpchapo** [gcgarner/IOTstack#61]
I have input the incorrect access token for dropbox, how do i change/reinstall please?

**Comment by gcgarner** [comment]
Have a look in your home folder for a file called `.dropbox ...` (can't remember the exact name) you can find it by running `ls - l ~/` remove that file and run the Dropbox-uploaded.sh ` ~/Dropbox-Uploader/dropbox_uploader.sh` (not at my pc so please verify the path) and it will ask you for your api key again

**Comment by gajpchapo** [comment]
there's no files in home, in home/pi theres only directories, one of which is DropboxUploader.  If I browse in there's; CHANGELOG.md  Dockerfile.pi        dropShell.sh  README.md
Dockerfile    dropbox_uploader.sh  LICENSE       testUnit.sh
Please advise?

**Comment by gcgarner** [comment]
If there is no dot file (hidden file) called something like .dropbox something (in /home/pi/) (do an ls -al in your home directory, I forgot to add the - al to show all files) the you should just be able the run the dropbox_uploader.sh and it should ask you for your api key again

**Comment by gajpchapo** [comment]
there's no .dropbox.  When I re-run script is says it's already loaded

**Comment by gcgarner** [comment]
I'll send you a screenshot when I'm home

**Comment by gajpchapo** [comment]
ok, thanks

**Comment by gcgarner** [comment]
make sure you are running the latest version of the project [link](https://github.com/gcgarner/IOTstack/wiki/Updating-the-Project)

`ls -al ~/`
![image](https://user-images.githubusercontent.com/46672225/68545218-9b7f1080-03d3-11ea-829b-654770c5449f.png)

remove the old file
`rm ~/.dropbox_uploader`

rerun the dropbox uploader
`~/Dropbox-Uploader/dropbox_uploader.sh`
![image](https://user-images.githubusercontent.com/46672225/68545272-1c3e0c80-03d4-11ea-8585-f3eecae6d016.png)

**Comment by gcgarner** [comment]
I added this to the wiki under backups

**Comment by gajpchapo** [comment]
no .dropbox_uploader here
![uploader](https://user-images.githubusercontent.com/29310213/68551021-43123800-0400-11ea-8241-2b1cf9b2e2ae.JPG)

Only difference, if significant, is that I didn't work of Raspbian Lite as I need Chrome for further elements of my project?

**Comment by gcgarner** [comment]
what is the output when you run `~/Dropbox-Uploader/dropbox_uploader.sh` ?

**Comment by gajpchapo** [comment]
Hi Graham,

I ran ~/Dropbox-Uploader/dropbox_uploader.sh info and it picked off where I needed it to, asking for the API.  I inserted and it saved.  Seems okay now.

Will now write a cron job and see how we go.

Thanks for your help.

**Comment by gcgarner** [comment]
not a problem, I learned how to better use Dropbox-Uploader in the process

 I've update the wiki based on this thread
