### ISSUE TITLE
Correct process for updating is not clear

### ISSUE THREAD

**Issue by Paraphraser** [gcgarner/IOTstack#64]
Although the Wiki covers:

```
cd ~/IOTstack
git checkout `git ls-files -m`
git pull origin master
```

It isn't clear what should happen next. Is it just executing:

```
~/IOTstack/scripts/update.sh
```

or is there a more appropriate procedure involving the stop/start/restart scripts?

**Comment by gcgarner** [comment]
I think I wrote that quite poorly. I'll spend some time improving the writeup on the wiki.

The update script only pulls the new base image from docker.

After the git pull you should rebuild the stack from the menu, when asked for the overwrite option select either full overwrite or keep env files.

I'll fix the write up this morning

**Comment by gcgarner** [comment]
Please have a look at the updated wiki entry and let me know if it is cleared and if you have any recommendations (besides my misspelling in the menu picture)

there is a note at the top if you ran 
```bash
git checkout  `git ls-files -m`
```
It would have removed your duckdns token, you will need to reinsert it. The new update procedure will not remove it in future

**Comment by Paraphraser** [comment]
The changes to the Wiki help. A lot. Thanks.

**Comment by gcgarner** [comment]
Thanks for reviewing
