### ISSUE TITLE
Portainer looks like it keeps restarting

### ISSUE THREAD

**Issue by Paraphraser** [gcgarner/IOTstack#67]
I keep seeing this pattern (make sure you scroll right to see the STATUS column):

```
$ docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                  PORTS                                                                                       NAMES
fa54039f64b0        influxdb:latest         "/entrypoint.sh infl…"   11 hours ago        Up 11 hours             0.0.0.0:2003->2003/tcp, 0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp                      influxdb
adb9e32f1ed1        pihole/pihole:latest    "/s6-init"               11 hours ago        Up 11 hours (healthy)   0.0.0.0:53->53/udp, 0.0.0.0:53->53/tcp, 0.0.0.0:67->67/udp, 443/tcp, 0.0.0.0:8089->80/tcp   pihole
881426b293bf        eclipse-mosquitto       "/docker-entrypoint.…"   11 hours ago        Up 11 hours             0.0.0.0:1883->1883/tcp, 0.0.0.0:9001->9001/tcp                                              mosquitto
ee076cb574b9        portainer/portainer     "/portainer"             11 hours ago        Up 3 minutes            0.0.0.0:9000->9000/tcp                                                                      portainer
bf72b049c827        iotstack_nodered        "npm start -- --user…"   11 hours ago        Up 11 hours             0.0.0.0:1880->1880/tcp                                                                      nodered
87c37d8bfcb9        grafana/grafana:6.3.6   "/run.sh"                11 hours ago        Up 11 hours             0.0.0.0:3000->3000/tcp                                                                      grafana
```

All containers CREATED an arbitrary number of hours ago. All containers **except** Portainer reporting a STATUS of having been running continuously since creation.

This pattern suggests that the Portainer container is restarting more frequently than other services. Please don't misinterpret this as me saying there is evidence that Portainer is **constantly** restarting in some kind of fast loop. It isn't. It can sometimes run for hours but it will eventually become the odd guy out in the list.

Is this the expected behaviour or does it suggest a problem?

Also, neither of the following work:

```
$ docker exec -it portainer sh
$ docker exec -it portainer bash
```

I had hoped to get into a terminal session to nose around /var/log but couldn't figure out how to get into the Portainer container. The closest I could get was the event list of the web UI but it is a bit short on useful detail. The attached screen shot corresponds with the start of the "up 3 minutes" time period in the above "docker ps" output. Something obviously happened to cause Portainer to exit but as to what "status code 1" means ... ?

<img width="1183" alt="Screen Shot 2019-11-13 at 11 11 22" src="https://user-images.githubusercontent.com/34226495/68721538-cc935700-0606-11ea-8f26-3b99cfcfe707.png">

**Comment by gcgarner** [comment]
That restarting nature definitely not normal behaviour. I haven't noticed it myself on my stack. I stop and start so often with my testing I possibly never see it. It could be a rights issue.

There are currently 555 active issues on portainer and i couldn't find any mention of portainer restarting at random

Regarding the terminal, I had a look at portainers [github](https://github.com/portainer/portainer/issues/2768) and they don't include a terminal shell with their image

I will monitor and report back

**Comment by gcgarner** [comment]
i checked my portainer and my one also restarted 

```
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                 PORTS                                                                                       NAMES
3de765c8609f        pihole/pihole:latest    "/s6-init"               3 hours ago         Up 3 hours (healthy)   0.0.0.0:53->53/udp, 0.0.0.0:53->53/tcp, 0.0.0.0:67->67/udp, 443/tcp, 0.0.0.0:8089->80/tcp   pihole
ca46f38dda6d        iotstack_nginx          "nginx -g 'daemon of…"   12 hours ago        Up 12 hours            0.0.0.0:433->433/tcp, 0.0.0.0:8080->80/tcp                                                  nginx
36f477204b0f        influxdb:latest         "/entrypoint.sh infl…"   12 hours ago        Up 12 hours            0.0.0.0:2003->2003/tcp, 0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp                      influxdb
7851f3b5b9d3        eclipse-mosquitto       "/docker-entrypoint.…"   12 hours ago        Up 12 hours            0.0.0.0:1883->1883/tcp, 0.0.0.0:9001->9001/tcp                                              mosquitto
6d668a02836c        portainer/portainer     "/portainer"             12 hours ago        Up 3 hours             0.0.0.0:9000->9000/tcp                                                                      portainer
86bd211f3dab        grafana/grafana:6.3.6   "/run.sh"                12 hours ago        Up 12 hours            0.0.0.0:3000->3000/tcp                                                                      grafana
c801df0a79b5        iotstack_nodered        "npm start -- --user…"   12 hours ago        Up 12 hours            0.0.0.0:1880->1880/tcp                                                                      nodered
660aeefc08e5        raymondmm/tasmoadmin    "/init"                  2 days ago          Up 2 days              443/tcp, 0.0.0.0:8088->80/tcp                                                               tasmoadmin

```

guess its time to open up an issue on portainer's github page

**Comment by gcgarner** [comment]
opened issue

https://github.com/portainer/portainer/issues/3369

**Comment by itsconquest** [comment]
[Cntr ]( https://github.com/Mic92/cntr)could be a useful tool to you both, it allows you to get shell on a container when none is present in the image

**Comment by gcgarner** [comment]
Added this to the wiki, busy with investigation
