### ISSUE TITLE
Rclone / Google drive setup instructions not working

### ISSUE THREAD

**Issue by Custom3DProducts** [gcgarner/IOTstack#74]
Trying to get rclone and google drive setup and launched automatically per the instructions linked. 
Google drive connection does work.
When trying to get the auto mounting to work I am having issues. Specifically at the `systemctl --user enable rclone@gdrive`

to start my systemd file is located at 
`home/pi/.config/systemd/user/rclone@.service` per the instructions

when running the `systemctl --user enable rclone@gdrive` command I initially got this 
`Failed to enable unit: Unit file /home/pi/.config/systemd/user/default.target.wa                                            nts/rclone@gdrive.service does not exist.`

So I created the file
`sudo mkdir -p ~/.config/systemd/user/default.target.wants/rclone@gdrive.service`

that did not work because then I got this
`Failed to enable unit: File /home/pi/.config/systemd/user/default.target.wants/rclone@gdrive.service already exists.`

So I removed just the `rclone@gdrive.service` file and tried again
` sudo systemctl --user enable rclone@gdrive
Failed to connect to bus: No such file or directory`

There is nothing in my directory ` /home/pi/.config/systemd/user/default.target.wants`
and my rclone file `rclone@.service` is still in the user directory filled with the text from the tutorial

I am unsure how to proceed as the directions, I know they are 3rd party, dont provide any info or tips on what to do if you get stuck. Ive googled this and tried to track down info before posting this issue but it seems this isnt really popular yet. 
Thank you for any help you can provide!

**Comment by gcgarner** [comment]
@Custom3DProducts I'd be glad to help. Firstly the automounting of the rclone is not necessary for the backup script to work. This is was not stated in the wiki and I have amended it to reflect that.

Could you confirm that you are able to get a successful output from: ` rclone ls --max-depth 1 gdrive:

I will go through the setup again on my side and report back

**Comment by gcgarner** [comment]
I did some testing on my side and i couldn't get the @ operator to work as the guide suggested. also i had to drop the max size operator

I hard coded the service, could you please test the following:

(I'm writing this out so i can copy it into the wiki)

```bash
mkdir -p ~/.config/systemd/user
nano ~/.config/systemd/user/gdrive.service
```
copy the following code into the editor, save and exit

```
[Unit]
Description=rclone: Remote FUSE filesystem for cloud storage
Documentation=man:rclone(1)

[Service]
Type=notify
ExecStartPre=/bin/mkdir -p %h/mnt/gdrive
ExecStart= \
  /usr/bin/rclone mount \
  --fast-list \
  --vfs-cache-mode writes \
  gdrive: %h/mnt/gdrive

[Install]
WantedBy=default.target
```
enable with (no sudo)
```bash
systemctl --user enable gdrive.service
```
start with `systemctl --user start gdrive.service`

**Comment by gcgarner** [comment]
should this work for you as well i can add it to the script to create the relevant service and then the user can just start it after they have configured the setup

**Comment by Custom3DProducts** [comment]
I will try it out right now. Thank you very much for your help! 
I do get a successful output from `rclone ls --max-depth 1 gdrive:`
on to testing the rest

**Comment by gcgarner** [comment]
Okay great, I think it is a case that the "@" operator doesn't work on Raspbian. they were trying to be fancy and write one service to mount multiple drives. with the hard-coded version you only get one

**Comment by Custom3DProducts** [comment]
I deleted all other files and directories under ` ~/.config/systemd/user/` there was only the ones from my attempts at getting it working on the other tutorial. 
Added your file to `nano ~/.config/systemd/user/gdrive.service`
It would not let me save the file without adding `"sudo" nano ~/.config/systemd/user/gdrive.service`

saved the file but back to
 `pi@raspberrypi:~ $ systemctl --user enable gdrive.service
Failed to enable unit: Unit file /home/pi/.config/systemd/user/default.target.wants/gdrive.service does not exist.`

**Comment by Custom3DProducts** [comment]
I get this in that file without using sudo
`[ File '/home/pi/.config/systemd/user/gdrive.service' is unwritable ]`

**Comment by gcgarner** [comment]
I had a look at your original post, you used sudo to create the folder the first time and the directories were created as root. As a result "pi" don't have the rights to edit that directory.

There is a simple fix you can run `sudo chown -R pi:pi ~/.config/` to set all the rights to "pi"

In general whenever using mkdir first run it without sudo to test if you have the rights and only use sudo if you have to 

there is a super handy bash function i use all the time and that is `!!`, !! is the last instruction you executed in the terminal so if it tells you that you dont have the rights then you run `sudo !!`

like this:
![image](https://user-images.githubusercontent.com/46672225/68994068-489bd200-0887-11ea-9d3c-a181e57d7b9f.png)

**Comment by Custom3DProducts** [comment]
You are the man! Silly mistake on my part.
`pi@raspberrypi:~ $ sudo chown -R pi:pi ~/.config/
pi@raspberrypi:~ $ cd .config
pi@raspberrypi:~/.config $ rm -rf systemd
pi@raspberrypi:~/.config $ ls -a
.  ..  rclone
pi@raspberrypi:~/.config $ cd rclone
pi@raspberrypi:~/.config/rclone $ ls -a
.  ..  rclone.conf
pi@raspberrypi:~/.config/rclone $ nano rclone.conf
pi@raspberrypi:~/.config/rclone $ cd
pi@raspberrypi:~ $ mkdir -p ~/.config/systemd/user
pi@raspberrypi:~ $ nano ~/.config/systemd/user/gdrive.service
pi@raspberrypi:~ $ systemctl --user enable gdrive.service
Created symlink /home/pi/.config/systemd/user/default.target.wants/gdrive.service → /home/pi/.config/systemd/user/gdrive.service.
pi@raspberrypi:~ $ systemctl --user start gdrive.service
pi@raspberrypi:~ $
`

**Comment by Custom3DProducts** [comment]
now shall I follow the ending on the tutorial to get the auto start up at login working?

**Comment by gcgarner** [comment]
basically what you just did was write a service and enabled it by running ` systemctl --user enable gdrive.service` and you made that service run at boot. So from now on (until you disable it) rclone will mount your google drive in ~/mnt/gdrive

the way the backup script works is it calls rclone itself 
```bash
if [ -f ./backups/rclone ]; then
	echo "uploading to Google Drive"
	rclone -P copy ./backups/$backupfile gdrive:/IOTstackBU/
fi
```
All you need for this to work is to have a valid rclone setup, no service required. The script tests for the empty file called ./backups/rclone and if it is there it calls rclone

**Comment by gcgarner** [comment]
I've update the wiki on getting rclone running. Please could you have a look if it makes more sense and report back
https://github.com/gcgarner/IOTstack/wiki/Backups

If you are happy could you close the issue

**Comment by Custom3DProducts** [comment]
Awesome, that is excellent. 
I appreciate your prompt help on this issue.

**Comment by gcgarner** [comment]
glad i could help
