### ISSUE TITLE
Grafana - map grafana.ini?

### ISSUE THREAD

**Issue by simonlock** [gcgarner/IOTstack#75]
Would it be possible to map the grafana.ini file locally within IOTstack? I'm running an Nginx reverse proxy with Lets Encrypt for IOTstack apps and it's my understanding that this file will need to be edited to specify as a subpath. e.g. https://domainname/grafana
This is what's reported by Nginx:
" If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath
"

**Comment by gcgarner** [comment]
According to the grafana website for docker you can set all the grafana.ini settings from the env file [link](https://grafana.com/docs/installation/docker/#configuration)

All the configurations are listed on their [config site](https://grafana.com/docs/installation/configuration/)

in theory you could add to IOTstack/services/grafana/grafana.env
```
GF_SERVER_ROOT_URL=http://address:3000/grafana
GF_SERVER_SERVE_FROM_SUB_PATH=true
```
(if your proxy is in your docker network then the address would be 'grafana', if your proxy is not in a container then it would be 'localhost')

After editing the env file you can run `docker-compose up -d` to recreate with the new settings

Would you mind sharing your proxy config? I've started on letsencrypt container (from linuxserver) but havent make much progress. I got stuck when hassio wants to be a subdomain and not a subfolder

**Comment by simonlock** [comment]
Thanks, Graham that did the trick. I'm running Nginx outside of containers and validating my LE certificate, using the Certbot DNS challenge method against Cloudflare who manages the DNS for my hosted domain. For IOTstack running on my Pi, I'm using a subdomain of my hosted domain called "iot"; the apps are subfolders of this subdomain.

I'm not at all an expert but please find attached my Nginx reverse proxy config:
[reverse.txt](https://github.com/gcgarner/IOTstack/files/3855474/reverse.txt)

**Comment by gcgarner** [comment]
I'll add this to the letsencrypt image i already have going. That one is prebuilt to validate and issue certificates against duckdns (does others as well but im sticking with the the duckdns theme)

I added those settings to the latest grafana.env template.

Thanks for verifying the functionality.
