### ISSUE TITLE
rsync failure with "Preserve Environment and Config file"

### ISSUE THREAD

**Issue by ikout** [gcgarner/IOTstack#82]
When selecting the "Preserve Environment and Config file" there is the following error/message shown at the cli for all docker-compose.yml entries:
```
...
Adding portainer container
...pulled portainer excluding env file
./menu.sh: line 53: *.conf: command not found
rsync: --exclude: missing argument
rsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]
Adding nodered container
...pulled nodered excluding env file
./menu.sh: line 53: *.conf: command not found
rsync: --exclude: missing argument
rsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]
....
```

The issue seems to be at the syntax of the rsync command for the confidence files:
`rsync -a -q .templates/$1/ services/$1/ --exclude 'build.sh' --exclude '$1.env' --exclude $(*.conf)
`

The "--exclude $(*.conf)" is probably wrong and it should be "--exclude '*.conf' "

**Comment by gcgarner** [comment]
Thanks for spotting that, I dont know how on earth I messed that one up. I tested that as well ...

i've pushed an update to fix that
