### ISSUE TITLE
How to stop/disable or "reset" hassio?

### ISSUE THREAD

**Issue by ikout** [gcgarner/IOTstack#83]
Sorry if I missed this at the wiki pages but how I can stop/disable or even reset/remove Hassio once installed with the script?
I like the idea an integration of these containers with this script but I want to do some testing and to reset the setup but I cannot stop the Hassio docker images...

I can only stop them for a while until they are restarted:
```
pi@pi-iot:~/IOTstack $ docker stop hassio_dns hassio_supervisor
hassio_dns
hassio_supervisor
pi@pi-iot:~/IOTstack $ 
pi@pi-iot:~/IOTstack $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
pi@pi-iot:~/IOTstack $ 
pi@pi-iot:~/IOTstack $ docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
820f1e465501        homeassistant/armv7-hassio-dns:1        "coredns -conf /conf…"   4 seconds ago       Up 2 seconds                            hassio_dns
3b03a6bd6ee7        homeassistant/armv7-hassio-supervisor   "/bin/entry.sh pytho…"   40 hours ago        Up 9 seconds                            hassio_supervisor
pi@pi-iot:~/IOTstack $ 
```
 
I'm I missing something?

Thanks

**Comment by gcgarner** [comment]
Hassio has its own service that makes **very** sure it is running

You can stop it with the following:

```bash
sudo systemctl stop hassio-supervisor.service
sudo systemctl disable hassio-supervisor.service
```

This will stop the service and disable it from starting on the next boot

Next you need to stop the hassio_dns and hassio_supervisor

```bash
docker stop hassio_supervisor
docker stop hassio_dns
```

If you want to remove the containers

```bash
docker rm hassio_supervisor
docker rm hassio_dns
```

The local files and volumes are stored in /usr/local/share/, i think its /usr/local/share/hassio

you can check in Portainer for any other hassio containers and images and clean them up there

I'll update the wiki with this info

**Comment by ikout** [comment]
yes, I was able to find that as well searching on the generic Hassio setup.
I was not sure if you had any changes due to the setup done by the script.

Based one the service file " /usr/sbin/hassio-supervisor" the data are kept at the "/usr/share/hassio":
`DATA="$(jq --raw-output '.data // "/usr/share/hassio"' ${CONFIG_FILE})"`
 
After doing these "clean ups" someone should still be able to re-run your script to re-install Hassio?
(FYI, I'll try that soon :) )

**Comment by gcgarner** [comment]
All i did for the install was add a menu to select the device type. then i call their installer shell script

I did the install several times while testing with and without cleanups and they did work. I think i should add a "uninstall" from the menu

**Comment by ikout** [comment]
I've tried the steps and re-installed it from the scrip.
It added the containers again for the "hassio_supervisor" and "hassio_dns" but the main container that is the actual Home Assistant "homeassistant" was not added again... :(

I tried several attempts but nothing... Due to time constraints I'm moving on and re-write the SD to do a clean setup....


If you update the script with an un-install option I'm OK to test it on a different SD/Setup :) in case any of my steps caused issues.

BTW, I believe that one more stop/rm command is needed for the homeassistant:
 ```
docker stop homeassistant
docker rm homeassistant
```

**Comment by sebi5361** [comment]
@ikout: I had the same issue, but rebooting my Pi after the installation solved the issue..

**Comment by gcgarner** [comment]
Thanks all, I've updated the wiki entry on how to remove hassio
