### ISSUE TITLE
Why `Disable Swap` doen't last after a reboot?

### ISSUE THREAD

**Issue by sebi5361** [gcgarner/IOTstack#85]
On my Raspberry Pi 3 Model B+, I have noticed that once the swap file is being removed (using the miscellaneous command `disable swap`), it will turn back after my Pi reboots (I use `htop` to reassess the swap file size). Wouldn't it be better if the swap file keeps being removed between two reboots?

**Comment by gcgarner** [comment]
I had a look at my system and it appears that my logfile recreates on reboot as well. To top it off my log2ram seems to have died.

I'll see what i can do to resolve it

**Comment by gcgarner** [comment]
I've changed the code from
```bash
		sudo dphys-swapfile swapoff
		sudo dphys-swapfile uninstall
		sudo update-rc.d dphys-swapfile remove
		echo "Swap file has been removed"
```
to 

```bash
		sudo dphys-swapfile swapoff
		sudo dphys-swapfile uninstall
		sudo update-rc.d dphys-swapfile remove
                sudo systemctl disable dphys-swapfile
		echo "Swap file has been removed"
```
That appears to so the job properly. I'll push when I'm done with the PR for the backups.

now i need to figure what log2ram's problem is

**Comment by gcgarner** [comment]
... will close after i push the changes

**Comment by gcgarner** [comment]
pushed update
