### ISSUE TITLE
Running the backup script from cron does not backup Influx databases

### ISSUE THREAD

**Issue by Paraphraser** [gcgarner/IOTstack#88]
I have found a problem running the backup script from cron.

I made a copy of docker\_backup.sh in ~/bin under the name pmk\_docker\_backup. The only change to the script was to add these lines after the "rclone" area:

```
#-------- pmk local backup to server ------
scp ./backups/$backupfile pmk@server:./iot-hub/backups
```

This copies the current backup file across my in-house network. This is a list of backup files on the target machine:

```
-rw-r--r--  1 pmk  staff  159792704 Nov 17 23:08 backup-2019-11-17_2307.tar.gz
-rw-r--r--  1 pmk  staff  160670938 Nov 18 16:55 backup-2019-11-18_1654.tar.gz
-rw-r--r--  1 pmk  staff  161569478 Nov 18 23:01 backup-2019-11-18_2300.tar.gz
-rw-r--r--  1 pmk  staff  162903355 Nov 19 12:26 backup-2019-11-19_1226.tar.gz
-rw-r--r--  1 pmk  staff   90037626 Nov 19 23:00 backup-2019-11-19_2300.tar.gz
-rw-r--r--  1 pmk  staff   90597091 Nov 20 22:55 backup-2019-11-20_2254.tar.gz
-rw-r--r--  1 pmk  staff   90598200 Nov 20 23:00 backup-2019-11-20_2300.tar.gz
-rw-r--r--  1 pmk  staff   90671336 Nov 20 23:01 backup-2019-11-20_2301.tar.gz
-rw-r--r--  1 pmk  staff  165170858 Nov 20 23:02 backup-2019-11-20_2302.tar.gz
-rw-r--r--  1 pmk  staff   90738608 Nov 20 23:04 backup-2019-11-20_2304.tar.gz
-rw-r--r--  1 pmk  staff   16235837 Nov 20 23:06 backup-2019-11-20_2306.tar.gz
```

Notice the large variation in backup file sizes. The backup file size _should_ be around the 165,170,858 bytes of the third-to-last file.

Inspection of the backup files reveals the following:

* Files more than 100,000,000 bytes contain Influx *db* **and** *db_old* folders, and **both** folders are fully populated (expected behaviour);
* Files in the 90,000,000 bytes range only have files in *db* **or** *db_old* **but not both**; and
* The last backup file in the list (16,235,837 bytes) contains no files in either *db* or *db_old*. Completely empty!

The file-size differences come down to how the backup script was invoked:

* If the script was run directly from the command line then it behaved as expected. Each successive run copied *db* to *db_old*, and then *db* was repopulated.
* If the script was invoked via cron then *db* was **never** populated so, assuming the starting position prior to setting up the cron job had both *db* and *db_old* populated:
	* The first cron run copied *db* to *db_old* but *db* was not repopulated (resulting in a "half size" backup);
	* The second and subsequent cron runs (with no intervening manual backup runs) resulted in both *db* and *db_old* being empty.

I have tested with both my customised *pmk\_docker\_backup* and the unmodified *docker\_backup.sh*. When executed from cron, the behaviour of both scripts is the same (ie this isn't "finger trouble" in my customised script).

Here is the crontab (with lines for the modified and original backup scripts):

```
#min	hour    mday    month   wday    command
6	23	*	*	*	./bin/pmk_docker_backup >>./Logs/pmk_docker_backup.log 2>&1
18	23	*	*	*	./IOTstack/scripts/docker_backup.sh >>./Logs/docker_backup.log 2>&1
```

Note that each cron task appends to a log file. Initially, that was unrevealing - until I edited *backup\_influxdb.sh* to remove all the stdout+stderr redirects to /dev/null. Then it became far more interesting:

```
~/IOTstack ~
Moving old influxdb backups if they exist
rm: cannot remove '/home/pi/IOTstack/backups/influxdb/db_old/*': No such file or directory
mv: cannot stat '/home/pi/IOTstack/backups/influxdb/db/*': No such file or directory
backing up influxdb database
the input device is not a TTY
influxdb backup complete
compressing stack folders
backup saved to ./backups/backup-2019-11-20_2318.tar.gz
16M	./backups/backup-2019-11-20_2318.tar.gz
last five backup files are saved in ~/IOTstack/backups
~
```

The critical error appears to be "the input device is not a TTY". I found some [information that may be relevant](https://stackoverflow.com/questions/43099116/error-the-input-device-is-not-a-tty) but which I do not pretend to understand. I hope it makes sense to you.

A couple of observations:

1. It seems likely that _anyone_ relying on running the backup script from cron (whether original or modified) is probably not getting their Influx databases backed-up.
2. When I write my own scripts, I try to avoid using redirects to null because of the way it can so easily hide errors and lull you into a false sense of security. What I usually do is either redirect to a log file in cron (as per the crontab lines above) or include lines like the ones below near the start of the script:

```
# declare a log file
LOGFILE="$HOME/Logs/example.log"

# ensure that the log exists
touch "$LOGFILE"

# redirect stdout and stderr to it
exec >> "$LOGFILE"
exec 2>> "$LOGFILE"
```

Of the two approaches, I mostly use the second because it then doesn't matter whether a script is run from the command line or cron: all logging information winds up in the same place.

Sure, the log grows over time and you may need to prune it occasionally but it's a good way to ensure you always have some evidence to review when you stumble across a problem.

A related technique I use when troubleshooting is:

```
$ tail -f $HOME/Logs/example.log &
```

and then trigger the action I'm trying to debug.

Anyway, that's just my 2¢ on the topic.

**Comment by gcgarner** [comment]
That's very interesting. I would have thought that calling it from the script vs from a crontab would be identical.

It would appear that a crontab cant invoke an interactive terminal "-it". When removing it the backup executes as it was intended to.

**Comment by Paraphraser** [comment]
I can confirm that removing "-it" has cured the problem. Thanks.
