### ISSUE TITLE
rsync failing when pulling container from template

### ISSUE THREAD

**Issue by ronnyandre** [gcgarner/IOTstack#89]
I have a fresh install of Raspbian completely updated and upgraded, and just fetched the IOTstack repository. I ran the Docker installation first, which ran successfully. I did as the installer said and rebooted.

After reboot, Docker is installed. However, when building the stack, I get the following error messages:

```
pi@raspberrypi:~ $ ./IOTstack/menu.sh 
Adding portainer container
...pulled full portainer from template
rsync: change_dir "/home/pi//.templates/portainer" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
cat: services/portainer/service.yml: No such file or directory
Adding influxdb container
...pulled full influxdb from template
rsync: change_dir "/home/pi//.templates/influxdb" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
cat: services/influxdb/service.yml: No such file or directory
```

And the error repeats itself for each container.

Can't seem to find anyone else with the same bug?

**Comment by ronnyandre** [comment]
Update:

I changed directory to sit inside the `IOTstack` folder and then run `./menu.sh`, and then I was more successful. However, I still get this:

```
touch: cannot touch './services/selection.txt': No such file or directory
Adding portainer container
...pulled full portainer from template
Adding influxdb container
...pulled full influxdb from template
```

**Comment by gcgarner** [comment]
To resolve the issue regarding executing the menu not inside the intended folder I think i will have to put a `pushd ~/IOTstack` at the top.  That will make sure that even if you execute it from the wrong directoy it will be fine.

Thanks for spotting the selection.txt issue. I assume the services directory exists already (because it does on my system) but in fact on a fresh install that directory wont exist yet. I will add a `mkdir -p services` in the script. That will fix it

**Comment by gcgarner** [comment]
I pushed up the relevant changes. You can do a `git pull origin master` from the project folder

**Comment by ronnyandre** [comment]
Thanks for your super quick reply and fix. I love IOTstack! Keep up the great work! 😄
