### ISSUE TITLE
Restart from NodeRED (exec-node)

### ISSUE THREAD

**Issue by fxg90** [gcgarner/IOTstack#9]
If possible: What is the best way to go to call "sudo reboot" with an exec-node?

**Comment by gcgarner** [comment]
You can think of the nodered container as a Virtual Machine. If you execute a "sudo reboot" in the nodered container it will only reboot the container not the host. The containers don't have control over the host.

Off the top of my head there is a very very dirty way of doing it. You could use the exec node to create a file in the container eg "touch /data/reboot". From the host you could write a script that checks to see if the file "~/IOTstack/volumes/nodered/data/reboot" exists. If it does then delete the file and reboot. Put that in a crontab that executes every minute. If you get it wrong you may end in an infinite restart.

**Comment by fxg90** [comment]
Ok. I never thought of it like a Virtual Machine, more like a service. 
Something like your "dirty hack" i also had in mind in case no host control. 
I would write a host service script which is looking for flags set by a container (in a writable file). 
In case of a system reboot, all flags had to be reset at first.
But as i see, there are some limitations with Docker, like you mentioned with the RTL_433 issue too.
Thank you again for your time and support!
