### ISSUE TITLE
Mosquitto logging and file/folder structure mapping

### ISSUE THREAD

**Issue by Paraphraser** [gcgarner/IOTstack#91]
I think there might be a few problems with Mosquitto. In summary (and in no particular order of priority):

* Portainer does not show a log for the Mosquitto instance.
* Mosquitto _is_ keeping a log but not where Portainer thinks it is.
* The volumes/mosquitto mapping doesn't seem to be working properly.
* Mosquitto is using Unix Epoch seconds for log timestamps. IMO, that's sub-optimal.

Now the detail. "Portainer > Containers > mosquitto > Logs" says:

```
	No logs available
```

This makes it the odd-container-out (at least for the ones I'm running):

"Portainer > Containers > mosquitto > inspect" gives me this LogPath:

```
LogPath /var/lib/docker/containers/881426b293bf53b2cc32ac333d674b91d389e74f336700fd0a5f3d4ad01777da/881426b293bf53b2cc32ac333d674b91d389e74f336700fd0a5f3d4ad01777da-json.log
```

When I try to view its contents:

```
$ sudo stat -c "%s" /var/lib/docker/containers/881426b293bf53b2cc32ac333d674b91d389e74f336700fd0a5f3d4ad01777da/881426b293bf53b2cc32ac333d674b91d389e74f336700fd0a5f3d4ad01777da-json.log
0

$ sudo cat /var/lib/docker/containers/881426b293bf53b2cc32ac333d674b91d389e74f336700fd0a5f3d4ad01777da/881426b293bf53b2cc32ac333d674b91d389e74f336700fd0a5f3d4ad01777da-json.log
$ 
```

it turns out to be empty - which agrees with what Portainer is saying.

What does the Mosquitto configuration file have to say on the logging issue?

```
$ cat ~/IOTstack/services/mosquitto/mosquitto.conf
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
#password_file /mosquitto/config/pwfile
```

Mosquitto has been told to keep a log. Let's take a peek:

```
$ docker exec -it mosquitto sh
# stat -c "%s" /mosquitto/log/mosquitto.log
357759

# tail -5 /mosquitto/log/mosquitto.log
1574557267: New client connected from 192.168.132.196 as SolaXRelay (p2, c1, k10).
1574557272: Client SolaXRelay disconnected.
1574557567: New connection from 192.168.132.196 on port 1883.
1574557567: New client connected from 192.168.132.196 as SolaXRelay (p2, c1, k10).
1574557572: Client SolaXRelay disconnected.
```

Definitely keeping a log, albeit in a suboptimal format (which I will come back to at the end). What does the Docker configuration for Mosquitto have to say about this?

```
$ cat ~/IOTstack/services/mosquitto/service.yml 
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "0"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto/:/mosquitto/
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
```

Unless I'm misreading that, it's telling me that the directory at "/mosquitto" _inside_ the container is mapped to the IOTstack-relative directory "./volumes/mosquitto" _outside_ the container. Right?

The situation _outside_ the container is:

```
$ ls -alR ~/IOTstack/volumes/mosquitto/
.:
total 20
drwxr-xr-x 5 root root 4096 Nov 10 21:30 .
drwxr-xr-x 8 root root 4096 Nov 11 11:18 ..
drwxr-xr-x 2 root root 4096 Nov 10 21:30 config
drwxr-xr-x 2 root root 4096 Nov 10 21:30 data
drwxr-xr-x 2 root root 4096 Nov 10 21:30 log

./config:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 5 root root 4096 Nov 10 21:30 ..
-rwxr-xr-x 1 root root    0 Nov 10 21:30 mosquitto.conf

./data:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 5 root root 4096 Nov 10 21:30 ..

./log:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 5 root root 4096 Nov 10 21:30 ..
```

Hmmm. Three directories and a zero-length .conf file. No log file, though. What's the story _inside_ the container?

```
$ docker exec -it mosquitto sh
# ls -alR /mosquitto/
.:
total 20
drwxr-xr-x    5 root     root          4096 Nov 10 10:30 .
drwxr-xr-x    1 root     root          4096 Nov 12 12:16 ..
drwxr-xr-x    2 root     root          4096 Nov 10 10:30 config
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 24 01:14 data
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 log

./config:
total 12
drwxr-xr-x    2 root     root          4096 Nov 10 10:30 .
drwxr-xr-x    5 root     root          4096 Nov 10 10:30 ..
-rw-r--r--    1 1000     1000           138 Nov 10 10:12 mosquitto.conf

./data:
total 12
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 24 01:14 .
drwxr-xr-x    5 root     root          4096 Nov 10 10:30 ..
-rw-------    1 mosquitt mosquitt        47 Nov 24 01:14 mosquitto.db

./log:
total 364
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 .
drwxr-xr-x    5 root     root          4096 Nov 10 10:30 ..
-rw-------    1 mosquitt mosquitt    358397 Nov 24 01:21 mosquitto.log
```

So, the _directories_ ("config", "data" and "log") are being mapped but the only _file_ making it through is "mosquitto.conf". But even that is hinky because "mosquitto.conf" has 138 bytes _inside_ the container and zero bytes _outside_ the container.

This has all the smell of an ownership and permissions problem but I suspect there may be a bit more to it. Here's a simple test to demonstrate that. First, from _inside_ the container, replicate the "log" directory with the name "test".

```
# cp -rp log test

# ls -ald log test		««« directory ownership by name
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 log
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 test

# ls -aldn log test		««« directory ownership by ID
drwxr-xr-x    2 1883     1883          4096 Nov 12 12:16 log
drwxr-xr-x    2 1883     1883          4096 Nov 12 12:16 test

# ls -alR log test		««« recursive structure
log:
total 368
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 .
drwxr-xr-x    6 root     root          4096 Nov 24 02:08 ..
-rw-------    1 mosquitt mosquitt    358397 Nov 24 02:06 mosquitto.log

test:
total 364
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 .
drwxr-xr-x    6 root     root          4096 Nov 24 02:08 ..
-rw-------    1 mosquitt mosquitt    358397 Nov 24 02:06 mosquitto.log
``` 

Compare the result from _outside_ the container:

```
$ ls -ald log test		««« directory ownership by name
drwxr-xr-x 2 root root 4096 Nov 10 21:30 log
drwxr-xr-x 2 1883 1883 4096 Nov 12 23:16 test

$ ls -aldn log test		««« directory ownership by ID
drwxr-xr-x 2    0    0 4096 Nov 10 21:30 log
drwxr-xr-x 2 1883 1883 4096 Nov 12 23:16 test

$ ls -alR log test		««« recursive structure
log:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 6 root root 4096 Nov 24 13:08 ..

test:
total 364
drwxr-xr-x 2 1883 1883   4096 Nov 12 23:16 .
drwxr-xr-x 6 root root   4096 Nov 24 13:08 ..
-rw------- 1 1883 1883 358397 Nov 24 13:06 mosquitto.log
```

So:

* _inside_ the container "log" and "test" are both owned by user "mosquitto" (1883) but _outside_ the container, "log" is owned by root while "test" is owned by userid 1883. After a "cp -rp"? Que?
* _inside_ the container, both copies of "mosquitto.log" are owned by user "mosquitto" (1883) with owner "rw" permissions but _outside_ the container, only the copy in "test" comes through (same ownership, same permissions) while the original in "log" doesn't show up at all.
 
While we're here, let's drill down into the "mosquitto.conf" file. Above, I listed the contents of this file in the ~IOTstack/services/mosquitto directory. Let's take a peek at what shows up _inside_ the container:

```
$ docker exec -it mosquitto sh
# cat /mosquitto/config/mosquitto.conf 
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
#password_file /mosquitto/config/pwfile
```

Identical to the one in *services*. So far, so good. But that file is also supposedly mapped into the *volumes* area. I've already noted "ls -l" results saying this file has non-zero length _inside_ the container but zero length _outside_ the container. Double-check:

```
$ stat -c "%s" ~/IOTstack/volumes/mosquitto/config/mosquitto.conf 
0

$ cat ~/IOTstack/volumes/mosquitto/config/mosquitto.conf
$
```

Meanwhile, the config file _inside_ the container has user- and group-ids of 1000, which seem to be mapping to "root" in the world _outside_ the container. Again, que?

I don't know about you but this all feels incredibly weird.

A couple of random thoughts:

* If I understand the Docker YAML correctly, mosquitto.conf turns up in three places:
	* ~/IOTstack/services/mosquitto/mosquitto.conf
	* /mosquitto/config/mosquitto.conf
	* ~/IOTstack/volumes/mosquitto/config/mosquitto.conf

	Another way of looking at it is:
	
	* All of /mosquitto/ is mapped to ~/IOTstack/volumes/mosquitto/, while
	* One component of /mosquitto/ (/mosquitto/config/mosquitto.conf) is mapped to ~/IOTstack/services/mosquitto/mosquitto.conf
	
	Which is the "original" mosquitto.conf? Can the same file be twice-mapped? Can a component of an already-mapped directory structure be mapped outside that structure?
	 
* Is any of this somehow related to #77 which covered a fair bit of the same ground:
	* The container restarting apparently traced to an ownership issue on ~/IOTstack/volumes/mosquitto;
	* Mention of owner-ID 1883; and
	* Changes to the volumes mappings.

I'm not seeing the container restarting but I am hot on the trail of an unusual number of socket errors reported by mosquitto; which is why I wanted the log; which is why I went down this rabbit-hole. But I'll save the socket errors detail for another issue.

### A related request

In the earlier "tail" output from mosquitto.log I suggested that the format was sub-optimal. That's because the timestamps are expressed in seconds since the Unix Epoch. I didn't think that was helpful for debugging so I fixed it:

```
$ echo "log_timestamp_format %Y-%m-%dT%H:%M:%S" >>~/IOTstack/services/mosquitto/mosquitto.conf
$ docker restart mosquitto
```

The log file _inside_ the container now expresses timestamps in local time.
 
```
$ docker exec -it mosquitto sh
# tail -5 /mosquitto/log/mosquitto.log 
2019-11-24T02:52:06: New connection from 172.18.0.1 on port 1883.
2019-11-24T02:52:06: New connection from 172.18.0.1 on port 1883.
2019-11-24T02:52:06: New client connected from 172.18.0.1 as mqtt_ea8d93ed.35022 (p1, c1, k60).
2019-11-24T02:52:06: New client connected from 172.18.0.1 as mqtt_8ce59dcc.c9c5e (p1, c1, k60).
2019-11-24T02:52:06: New client connected from 172.18.0.1 as mqtt_39f79ab1.35b336 (p1, c1, k60).
``` 

I did not know whether there was a good reason for using seconds-based timestamps as the default so I decided not to turn this into a PR. However, if you agree that localtime representation would be better, you could consider adding this as the default.

**Comment by Paraphraser** [comment]
On the topic of getting Mosquitto to write logs with human-readable timestamps, I just realised that the timestamps in the example output above are UTC. Personally, I could live with that but I thought I'd draw attention to it in case you wanted to harmonise local time across all containers.

**Comment by gcgarner** [comment]
I think the issue is related to folder permissions. I've been working on getting the folder permissions in such a way that i can remove the use of sudo everywhere. Basically i want setup an ACL for the volumes directory. That should allow the pi user to copy and edit the files without sudo. This will also allow me to drop the user: "0" which was a workaround till now

I think the way i mapped the conf file and the datafile broke the nesting. I hope to have this fixed by Wednesday when i push the latest changes

**Comment by gcgarner** [comment]
I was hoping that the ACL would be a catch all for the folder permissions but alas it wasn't.

I'm going to have to add a new script that runs in the .templates folder that runs and sets the folder permissions for each volume structure. That way i can set the ownership tailored to each image. If you look at the very first commit of this project before the menu existed it had a folderfix.sh script to get the permissions correct. Guess I will have to resurrect it

**Comment by gcgarner** [comment]
I've been bombarding my mosquitto container with message for the last two days, with constant connects and disconnects with local clients. The logfile is 528K and so far i only have two socket errors, however I suspect its due to a few restarts that i've done

**Comment by Paraphraser** [comment]
Shouldn't this be in #99? No matter.

```
# confirm previous count
$ grep -i "Socket error on client" mosquitto.log|wc -l
179

# fetch updated log
pi@iot-hub:~ $ docker cp mosquitto:/mosquitto/log/mosquitto.log mosquitto.log

# count again
pi@iot-hub:~ $ grep -i "Socket error on client" mosquitto.log|wc -l
202
```

Unless your clients are other than EP32/ESP8266 then I can't think how/why my environment would be all that different.

LoRa gateway ~ 1 MQTT per 15 minutes. Solar monitor and temperature/pressure sensors ~ 1 per 5 minutes. Electricity monitor 1 per 10 seconds. All up maybe 400 per hour. Not really "bombarding".

Got me stumped.

**Comment by Paraphraser** [comment]
I can see an attempt to fix the Mosquitto mapping problem but I don't think it is working. At least, not on my RPi4.

Chapter and verse...

### Update

```
$ cd ~/IOTstack; git pull origin master
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 57 (delta 30), reused 41 (delta 17), pack-reused 0
Unpacking objects: 100% (57/57), done.
From https://github.com/gcgarner/IOTstack
 * branch            master     -> FETCH_HEAD
   3df64fd..249bc76  master     -> origin/master
Updating 3df64fd..249bc76
Fast-forward
 .native/rpieasy.sh                   | 18 ++++++++++++++++++
 .templates/diyhue/diyhue.env         |  2 ++
 .templates/diyhue/service.yml        | 14 ++++++++++++++
 .templates/mariadb/terminal.sh       |  2 +-
 .templates/mosquitto/directoryfix.sh | 15 +++++++++++++++
 .templates/mosquitto/service.yml     |  6 ++++--
 README.md                            | 69 +++++++++++++++++++++++++++++++++++++++++++--------------------------
 menu.sh                              | 45 ++++++++++++++++++++++++++++++++++++++-------
 scripts/docker_backup.sh             |  5 +++--
 9 files changed, 138 insertions(+), 38 deletions(-)
 create mode 100644 .native/rpieasy.sh
 create mode 100644 .templates/diyhue/diyhue.env
 create mode 100644 .templates/diyhue/service.yml
 create mode 100755 .templates/mosquitto/directoryfix.sh
```

### Run the menu

```
$ ./menu.sh 
~/IOTstack ~/IOTstack
checking for project update
From https://github.com/gcgarner/IOTstack
 * branch            master     -> FETCH_HEAD
Project is up to date
./menu.sh: line 55: getfacl: command not found
sudo: setfacl: command not found
./menu.sh: line 56: getfacl: command not found
sudo: setfacl: command not found
Adding portainer container
...portainer service not overwritten
Adding nodered container
...nodered service not overwritten
Adding influxdb container
...influxdb service not overwritten
Adding grafana container
...grafana service not overwritten
Adding mosquitto container
...mosquitto service not overwritten
...Running directoryfix.sh on mosquitto
...found user 0 setting ownership for old template
Adding pihole container
...pihole service not overwritten
docker-compose successfully created
run 'docker-compose up -d' to start the stack
~/IOTstack
```

Hmmmmm:

* What's that "getfacl: command not found"? Might need to come back to that.
* Noted "Running directoryfix.sh on mosquitto".

### Does Docker need to do anything?

```
$ docker-compose up -d
nodered is up-to-date
grafana is up-to-date
pihole is up-to-date
influxdb is up-to-date
portainer is up-to-date
mosquitto is up-to-date
```

No. All happy.

### Have the Mosqitto mappings been fixed?

```
$ ls -alR ~/IOTstack/volumes/mosquitto/
/home/pi/IOTstack/volumes/mosquitto/:
total 20
drwxr-xr-x 5 root root 4096 Nov 24 19:16 .
drwxr-xr-x 8 root root 4096 Nov 11 11:18 ..
drwxr-xr-x 2 root root 4096 Nov 10 21:30 config
drwxr-xr-x 2 root root 4096 Nov 10 21:30 data
drwxr-xr-x 2 root root 4096 Nov 10 21:30 log

./config:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 5 root root 4096 Nov 24 19:16 ..
-rwxr-xr-x 1 root root    0 Nov 10 21:30 mosquitto.conf

./data:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 5 root root 4096 Nov 24 19:16 ..

./log:
total 8
drwxr-xr-x 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x 5 root root 4096 Nov 24 19:16 ..
```

No. Double-check the situation _inside_ the container.

```

$ docker exec -it mosquitto sh
# ls -alR mosquitto/
mosquitto/:
total 20
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 .
drwxr-xr-x    1 root     root          4096 Dec  3 04:51 ..
drwxr-xr-x    2 root     root          4096 Nov 10 10:30 config
drwxr-xr-x    2 mosquitt mosquitt      4096 Dec  3 04:44 data
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 log

./config:
total 12
drwxr-xr-x    2 root     root          4096 Nov 10 10:30 .
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 ..
-rw-r--r--    1 1000     1000           177 Nov 24 02:56 mosquitto.conf

./data:
total 12
drwxr-xr-x    2 mosquitt mosquitt      4096 Dec  3 04:44 .
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 ..
-rw-------    1 mosquitt mosquitt        47 Dec  3 04:44 mosquitto.db

./log:
total 1216
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 .
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 ..
-rw-------    1 mosquitt mosquitt   1229492 Dec  3 05:01 mosquitto.log
```

Still only "mosquitto.conf" visible outside the container and that file is still suffering from being zero-length outside the container.

### Let's get back to "getfacl"

Is that installed anywhere?


```
$ which getfacl
$
```

No. Probably time to throw caution to the winds, do a full update and then install the ACL package.

```
$ sudo apt update
$ sudo apt full-upgrade

.. reboot ..

$ sudo apt install acl

$ which getfacl
/usr/bin/getfacl
```

Re-run the menu again to see if having access to "getfacl" makes any difference.

```
$ cd IOTstack/; ./menu.sh 
~/IOTstack ~/IOTstack
checking for project update
From https://github.com/gcgarner/IOTstack
 * branch            master     -> FETCH_HEAD
Project is up to date
Adding portainer container
...portainer service not overwritten
Adding nodered container
...nodered service not overwritten
Adding influxdb container
...influxdb service not overwritten
Adding grafana container
...grafana service not overwritten
Adding mosquitto container
...mosquitto service not overwritten
...Running directoryfix.sh on mosquitto
...found user 0 setting ownership for old template
Adding pihole container
...pihole service not overwritten
docker-compose successfully created
run 'docker-compose up -d' to start the stack
~/IOTstack

$ docker-compose up -d
pihole is up-to-date
portainer is up-to-date
nodered is up-to-date
grafana is up-to-date
mosquitto is up-to-date
influxdb is up-to-date
```

Errors have gone away. Has the Mosquitto container situation changed?

```
$ ls -alR ~/IOTstack/volumes/mosquitto/
/home/pi/IOTstack/volumes/mosquitto/:
total 20
drwxr-xr-x+ 5 root root 4096 Nov 24 19:16 .
drwxr-xr-x+ 8 root root 4096 Nov 11 11:18 ..
drwxr-xr-x+ 2 root root 4096 Nov 10 21:30 config
drwxr-xr-x+ 2 root root 4096 Nov 10 21:30 data
drwxr-xr-x+ 2 root root 4096 Nov 10 21:30 log

./config:
total 8
drwxr-xr-x+ 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x+ 5 root root 4096 Nov 24 19:16 ..
-rwxr-xr-x  1 root root    0 Nov 10 21:30 mosquitto.conf

./data:
total 8
drwxr-xr-x+ 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x+ 5 root root 4096 Nov 24 19:16 ..

./log:
total 8
drwxr-xr-x+ 2 root root 4096 Nov 10 21:30 .
drwxr-xr-x+ 5 root root 4096 Nov 24 19:16 ..

$ docker exec -it mosquitto sh 
# ls -alR mosquitto/
mosquitto/:
total 20
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 .
drwxr-xr-x    1 root     root          4096 Dec  3 04:51 ..
drwxr-xr-x    2 root     root          4096 Nov 10 10:30 config
drwxr-xr-x    2 mosquitt mosquitt      4096 Dec  3 05:24 data
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 log

mosquitto/config:
total 12
drwxr-xr-x    2 root     root          4096 Nov 10 10:30 .
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 ..
-rw-r--r--    1 1000     1000           177 Nov 24 02:56 mosquitto.conf

mosquitto/data:
total 12
drwxr-xr-x    2 mosquitt mosquitt      4096 Dec  3 05:24 .
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 ..
-rw-------    1 mosquitt mosquitt        47 Dec  3 05:24 mosquitto.db

mosquitto/log:
total 1220
drwxr-xr-x    2 mosquitt mosquitt      4096 Nov 12 12:16 .
drwxr-xr-x    5 root     root          4096 Nov 24 08:16 ..
-rw-------    1 mosquitt mosquitt   1234766 Dec  3 05:31 mosquitto.log
# 
```

No. Still the original problem.

I keep coming back to and staring at this, and wondering...

```
    volumes:
      - ./volumes/mosquitto/:/mosquitto/
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
```

The fact that mosquitto.conf appears in three places (twice outside the container, once inside the container) with conflicting permissions and ownerships. That gives me pause.

```
$ ls -al ~/IOTstack/services/mosquitto/mosquitto.conf
-rw-r--r-- 1 pi pi 177 Nov 24 13:56 /home/pi/IOTstack/services/mosquitto/mosquitto.conf
$ ls -aln ~/IOTstack/services/mosquitto/mosquitto.conf
-rw-r--r-- 1 1000 1000 177 Nov 24 13:56 /home/pi/IOTstack/services/mosquitto/mosquitto.conf

$ ls -al ~/IOTstack/volumes/mosquitto/config/mosquitto.conf
-rwxr-xr-x 1 root root 0 Nov 10 21:30 /home/pi/IOTstack/volumes/mosquitto/config/mosquitto.conf
$ ls -aln ~/IOTstack/volumes/mosquitto/config/mosquitto.conf
-rwxr-xr-x 1 0 0 0 Nov 10 21:30 /home/pi/IOTstack/volumes/mosquitto/config/mosquitto.conf

# ls -al /mosquitto/config/mosquitto.conf 
-rw-r--r--    1 1000     1000           177 Nov 24 02:56 /mosquitto/config/mosquitto.conf
# ls -aln /mosquitto/config/mosquitto.conf 
-rw-r--r--    1 1000     1000           177 Nov 24 02:56 /mosquitto/config/mosquitto.conf
```

But the thing that most troubles me is the implied recursion. Yes, file systems are tree structures and yes, we typically use recursive algorithms to traverse them. But that doesn't mean that file systems inherently support recursion. I think of all the switches on various commands that support following or not following symlinks, or stopping when a duplicate iNode is encountered, or stopping when a volume boundary is crossed. 

In the scheme of things, the "config" directory is likely to be encountered first so I can easily imagine a bit of tie-breaking code stopping when it realises (a) it has seen "mosquitto.conf" before and (b) throwing up its electronic hands in horror when it can't resolve the permissions/ownership dilemma.

However, I would expect **some** evidence of this to turn up in a log. If it is, I can't find it.

**Comment by gcgarner** [comment]
Hello Phil

By the looks of your log you didnt full the new template for mosquitto

```bash
Adding mosquitto container
...mosquitto service not overwritten
...Running directoryfix.sh on mosquitto
...found user 0 setting ownership for old template
```

It says mosquitto not over written. The new template would say found user 1883. Could you check that you selected the "pull full template" option (remember you select it with the Spacebar then enter)

Re: setfacl

I assume you are running the Lite version of Rasbian. I took for granted that the ACL package would have been default with linux however seeing that the Lite version doesnt even include GIT (which is fundamental to linux) I should have double checked that

**Comment by Paraphraser** [comment]
Actually, from the three options at [https://www.raspberrypi.org/downloads/raspbian/](https://www.raspberrypi.org/downloads/raspbian/):

1. Raspbian Buster with desktop and recommended software
2. Raspbian Buster with desktop
3. Raspbian Buster Lite

I chose option 2.

If memory serves, I made two attempts to get option 1 but the download timed out each time. I thought words to the effect of "ah, stuff it" and gave option 2 a whirl. It downloaded OK so that's what I used.

I must say that I thought "recommended software" had more to do with "office" apps running in the desktop GUI than CLI functions like the ACL package. Seems I was wrong.

**Comment by gcgarner** [comment]
I double checked my installation and it looks like i have option 1 because I have office installed. I thought that the ACL came with because I have it on my system and i don't recall installing it explicitly. That isn't to say that it wasn't bundled with something else I installed. 

I'm thinking of rebuilding my system with the lite image to make sure that i have the minimum set of installed apps

**Comment by Paraphraser** [comment]
Probably time to close this issue. if I’ve understood the explanation correctly, the underlying cause is the mosquitto designer chose not to link the log so Portainer could see it, so there’s nothing to be done until that’s resolved.
