### ISSUE TITLE
Feature request - Blynk local server

### ISSUE THREAD

**Issue by 877dev** [gcgarner/IOTstack#94]
Hi,

Can this be added to the list?
https://github.com/blynkkk/blynk-server

Thanks

**Comment by gcgarner** [comment]
I'll add it on wednesday with my other updates

**Comment by gcgarner** [comment]
I did test this in the past and forgot that the docker image as is doesn't run on the pi. Going to add an issue to the project to see if there was a resolution

**Comment by gcgarner** [comment]
i managed to get the service working by making a custom Dockerfile. It looks like its working for now
