### ISSUE TITLE
I really like this IOTstack and I even create a video tutorial about it

### ISSUE THREAD

**Issue by peyanski** [gcgarner/IOTstack#98]
Hi there,

this is my video guide/tutorial - https://youtu.be/5JMNHuHv134
If you think that the video is helpful you can put it somewhere in the README/Wiki.

Either way keep up the good work.

Cheers,
Kiril

**Comment by gcgarner** [comment]
Awesome! Thanks I will add it to the README

**Comment by peyanski** [comment]
Wow Graham, great to hear that. 

I'm really glad that I'm able to help you somehow. 
If there is anything else that I can do - let me know!

Cheers,
Kiril

**Comment by gcgarner** [comment]
I updated the README, hope you go viral!

**Comment by peyanski** [comment]
Thank you for that.
I'll do my best to promote it and of course your work as well

**Comment by gcgarner** [comment]
added to README, closing thread
